// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// ACLClient is the ACL resource group of the Official UniFi OpenAPI surface.
type ACLClient interface {
	// CreateRule maps to POST /v1/sites/%s/acl-rules on the Official API.
	CreateRule(ctx context.Context, siteId string, body ACLRuleUpdate) (*ACLRule, error)
	// DeleteRule maps to DELETE /v1/sites/%s/acl-rules/%s on the Official API.
	DeleteRule(ctx context.Context, siteId string, aclRuleId string) error
	// GetRule maps to GET /v1/sites/%s/acl-rules/%s on the Official API.
	GetRule(ctx context.Context, siteId string, aclRuleId string) (*ACLRule, error)
	// GetRuleOrdering maps to GET /v1/sites/%s/acl-rules/ordering on the Official API.
	GetRuleOrdering(ctx context.Context, siteId string) (*ACLRuleOrdering, error)
	// GetRulePage maps to GET /v1/sites/%s/acl-rules on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
	GetRulePage(ctx context.Context, siteId string) ([]ACLRuleObject, error)
	// UpdateRule maps to PUT /v1/sites/%s/acl-rules/%s on the Official API.
	UpdateRule(ctx context.Context, siteId string, aclRuleId string, body ACLRuleUpdate) (*ACLRule, error)
	// UpdateRuleOrdering maps to PUT /v1/sites/%s/acl-rules/ordering on the Official API.
	UpdateRuleOrdering(ctx context.Context, siteId string, body ACLRuleOrdering) (*ACLRuleOrdering, error)
}

// aCLClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type aCLClient struct{ *apiClient }

var _ ACLClient = aCLClient{}

// ACL returns the ACL resource group.
func (c *apiClient) ACL() ACLClient {
	return aCLClient{c}
}

// CreateRule maps to POST /v1/sites/%s/acl-rules on the Official API.
func (c aCLClient) CreateRule(ctx context.Context, siteId string, body ACLRuleUpdate) (*ACLRule, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRule
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateRule: %w", err)
	}
	return &out, nil
}

// DeleteRule maps to DELETE /v1/sites/%s/acl-rules/%s on the Official API.
func (c aCLClient) DeleteRule(ctx context.Context, siteId string, aclRuleId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/%s", url.PathEscape(siteId), url.PathEscape(aclRuleId))), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteRule: %w", err)
	}
	return nil
}

// GetRule maps to GET /v1/sites/%s/acl-rules/%s on the Official API.
func (c aCLClient) GetRule(ctx context.Context, siteId string, aclRuleId string) (*ACLRule, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRule
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/%s", url.PathEscape(siteId), url.PathEscape(aclRuleId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetRule: %w", err)
	}
	return &out, nil
}

// GetRuleOrdering maps to GET /v1/sites/%s/acl-rules/ordering on the Official API.
func (c aCLClient) GetRuleOrdering(ctx context.Context, siteId string) (*ACLRuleOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRuleOrdering
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/ordering", url.PathEscape(siteId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetRuleOrdering: %w", err)
	}
	return &out, nil
}

// GetRulePage maps to GET /v1/sites/%s/acl-rules on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c aCLClient) GetRulePage(ctx context.Context, siteId string) ([]ACLRuleObject, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []ACLRuleObject
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/acl-rules", url.PathEscape(siteId))), &out); err != nil {
		return nil, fmt.Errorf("failed GetRulePage: %w", err)
	}
	return out, nil
}

// UpdateRule maps to PUT /v1/sites/%s/acl-rules/%s on the Official API.
func (c aCLClient) UpdateRule(ctx context.Context, siteId string, aclRuleId string, body ACLRuleUpdate) (*ACLRule, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRule
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/%s", url.PathEscape(siteId), url.PathEscape(aclRuleId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateRule: %w", err)
	}
	return &out, nil
}

// UpdateRuleOrdering maps to PUT /v1/sites/%s/acl-rules/ordering on the Official API.
func (c aCLClient) UpdateRuleOrdering(ctx context.Context, siteId string, body ACLRuleOrdering) (*ACLRuleOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRuleOrdering
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/ordering", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateRuleOrdering: %w", err)
	}
	return &out, nil
}

// ACLClientMock is a func-field test double implementing ACLClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type ACLClientMock struct {
	CreateRuleFunc         func(context.Context, string, ACLRuleUpdate) (*ACLRule, error)
	DeleteRuleFunc         func(context.Context, string, string) error
	GetRuleFunc            func(context.Context, string, string) (*ACLRule, error)
	GetRuleOrderingFunc    func(context.Context, string) (*ACLRuleOrdering, error)
	GetRulePageFunc        func(context.Context, string) ([]ACLRuleObject, error)
	UpdateRuleFunc         func(context.Context, string, string, ACLRuleUpdate) (*ACLRule, error)
	UpdateRuleOrderingFunc func(context.Context, string, ACLRuleOrdering) (*ACLRuleOrdering, error)
}

var _ ACLClient = (*ACLClientMock)(nil)

func (m *ACLClientMock) CreateRule(ctx context.Context, siteId string, body ACLRuleUpdate) (*ACLRule, error) {
	return m.CreateRuleFunc(ctx, siteId, body)
}

func (m *ACLClientMock) DeleteRule(ctx context.Context, siteId string, aclRuleId string) error {
	return m.DeleteRuleFunc(ctx, siteId, aclRuleId)
}

func (m *ACLClientMock) GetRule(ctx context.Context, siteId string, aclRuleId string) (*ACLRule, error) {
	return m.GetRuleFunc(ctx, siteId, aclRuleId)
}

func (m *ACLClientMock) GetRuleOrdering(ctx context.Context, siteId string) (*ACLRuleOrdering, error) {
	return m.GetRuleOrderingFunc(ctx, siteId)
}

func (m *ACLClientMock) GetRulePage(ctx context.Context, siteId string) ([]ACLRuleObject, error) {
	return m.GetRulePageFunc(ctx, siteId)
}

func (m *ACLClientMock) UpdateRule(ctx context.Context, siteId string, aclRuleId string, body ACLRuleUpdate) (*ACLRule, error) {
	return m.UpdateRuleFunc(ctx, siteId, aclRuleId, body)
}

func (m *ACLClientMock) UpdateRuleOrdering(ctx context.Context, siteId string, body ACLRuleOrdering) (*ACLRuleOrdering, error) {
	return m.UpdateRuleOrderingFunc(ctx, siteId, body)
}
