// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"iter"
	"net/url"
)

// ACLsClient is the ACLs resource group of the Official UniFi OpenAPI surface.
type ACLsClient interface {
	// CreateRule maps to POST /v1/sites/%s/acl-rules on the Official API.
	CreateRule(ctx context.Context, siteId string, body ACLRuleUpdate) (*ACLRule, error)
	// DeleteRule maps to DELETE /v1/sites/%s/acl-rules/%s on the Official API.
	DeleteRule(ctx context.Context, siteId string, aclRuleId string) error
	// GetRule maps to GET /v1/sites/%s/acl-rules/%s on the Official API.
	GetRule(ctx context.Context, siteId string, aclRuleId string) (*ACLRule, error)
	// GetRuleOrdering maps to GET /v1/sites/%s/acl-rules/ordering on the Official API.
	GetRuleOrdering(ctx context.Context, siteId string) (*ACLRuleOrdering, error)
	// ListRuleAll lazily drains every item from GET /v1/sites/%s/acl-rules, paging on demand; range it and break to stop early.
	ListRuleAll(ctx context.Context, siteId string) iter.Seq2[ACLRuleObject, error]
	// ListRulePage returns one page from GET /v1/sites/%s/acl-rules; nil opts fetches the first page at the default size.
	ListRulePage(ctx context.Context, siteId string, opts *ListOptions) (Page[ACLRuleObject], error)
	// UpdateRule maps to PUT /v1/sites/%s/acl-rules/%s on the Official API.
	UpdateRule(ctx context.Context, siteId string, aclRuleId string, body ACLRuleUpdate) (*ACLRule, error)
	// UpdateRuleOrdering maps to PUT /v1/sites/%s/acl-rules/ordering on the Official API.
	UpdateRuleOrdering(ctx context.Context, siteId string, body ACLRuleOrdering) (*ACLRuleOrdering, error)
}

// aCLsClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type aCLsClient struct{ *apiClient }

var _ ACLsClient = aCLsClient{}

// ACLs returns the ACLs resource group.
func (c *apiClient) ACLs() ACLsClient {
	return aCLsClient{c}
}

// CreateRule maps to POST /v1/sites/%s/acl-rules on the Official API.
func (c aCLsClient) CreateRule(ctx context.Context, siteId string, body ACLRuleUpdate) (*ACLRule, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRule
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateRule: %w", err)
	}
	return &out, nil
}

// DeleteRule maps to DELETE /v1/sites/%s/acl-rules/%s on the Official API.
func (c aCLsClient) DeleteRule(ctx context.Context, siteId string, aclRuleId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/%s", url.PathEscape(siteId), url.PathEscape(aclRuleId))), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteRule: %w", err)
	}
	return nil
}

// GetRule maps to GET /v1/sites/%s/acl-rules/%s on the Official API.
func (c aCLsClient) GetRule(ctx context.Context, siteId string, aclRuleId string) (*ACLRule, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRule
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/%s", url.PathEscape(siteId), url.PathEscape(aclRuleId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetRule: %w", err)
	}
	return &out, nil
}

// GetRuleOrdering maps to GET /v1/sites/%s/acl-rules/ordering on the Official API.
func (c aCLsClient) GetRuleOrdering(ctx context.Context, siteId string) (*ACLRuleOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRuleOrdering
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/ordering", url.PathEscape(siteId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetRuleOrdering: %w", err)
	}
	return &out, nil
}

// ListRuleAll lazily drains every item from GET /v1/sites/%s/acl-rules, paging on demand; range it and break to stop early.
func (c aCLsClient) ListRuleAll(ctx context.Context, siteId string) iter.Seq2[ACLRuleObject, error] {
	return listSeq[ACLRuleObject](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/acl-rules", url.PathEscape(siteId))), "")
}

// ListRulePage returns one page from GET /v1/sites/%s/acl-rules; nil opts fetches the first page at the default size.
func (c aCLsClient) ListRulePage(ctx context.Context, siteId string, opts *ListOptions) (Page[ACLRuleObject], error) {
	if err := c.check(ctx); err != nil {
		return Page[ACLRuleObject]{}, err
	}
	p, err := listPage[ACLRuleObject](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/acl-rules", url.PathEscape(siteId))), opts)
	if err != nil {
		return Page[ACLRuleObject]{}, fmt.Errorf("failed ListRulePage: %w", err)
	}
	return p, nil
}

// UpdateRule maps to PUT /v1/sites/%s/acl-rules/%s on the Official API.
func (c aCLsClient) UpdateRule(ctx context.Context, siteId string, aclRuleId string, body ACLRuleUpdate) (*ACLRule, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRule
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/%s", url.PathEscape(siteId), url.PathEscape(aclRuleId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateRule: %w", err)
	}
	return &out, nil
}

// UpdateRuleOrdering maps to PUT /v1/sites/%s/acl-rules/ordering on the Official API.
func (c aCLsClient) UpdateRuleOrdering(ctx context.Context, siteId string, body ACLRuleOrdering) (*ACLRuleOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRuleOrdering
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/ordering", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateRuleOrdering: %w", err)
	}
	return &out, nil
}

// ACLsClientMock is a func-field test double implementing ACLsClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type ACLsClientMock struct {
	CreateRuleFunc         func(context.Context, string, ACLRuleUpdate) (*ACLRule, error)
	DeleteRuleFunc         func(context.Context, string, string) error
	GetRuleFunc            func(context.Context, string, string) (*ACLRule, error)
	GetRuleOrderingFunc    func(context.Context, string) (*ACLRuleOrdering, error)
	ListRuleAllFunc        func(context.Context, string) iter.Seq2[ACLRuleObject, error]
	ListRulePageFunc       func(context.Context, string, *ListOptions) (Page[ACLRuleObject], error)
	UpdateRuleFunc         func(context.Context, string, string, ACLRuleUpdate) (*ACLRule, error)
	UpdateRuleOrderingFunc func(context.Context, string, ACLRuleOrdering) (*ACLRuleOrdering, error)
}

var _ ACLsClient = (*ACLsClientMock)(nil)

func (m *ACLsClientMock) CreateRule(ctx context.Context, siteId string, body ACLRuleUpdate) (*ACLRule, error) {
	return m.CreateRuleFunc(ctx, siteId, body)
}

func (m *ACLsClientMock) DeleteRule(ctx context.Context, siteId string, aclRuleId string) error {
	return m.DeleteRuleFunc(ctx, siteId, aclRuleId)
}

func (m *ACLsClientMock) GetRule(ctx context.Context, siteId string, aclRuleId string) (*ACLRule, error) {
	return m.GetRuleFunc(ctx, siteId, aclRuleId)
}

func (m *ACLsClientMock) GetRuleOrdering(ctx context.Context, siteId string) (*ACLRuleOrdering, error) {
	return m.GetRuleOrderingFunc(ctx, siteId)
}

func (m *ACLsClientMock) ListRuleAll(ctx context.Context, siteId string) iter.Seq2[ACLRuleObject, error] {
	return m.ListRuleAllFunc(ctx, siteId)
}

func (m *ACLsClientMock) ListRulePage(ctx context.Context, siteId string, opts *ListOptions) (Page[ACLRuleObject], error) {
	return m.ListRulePageFunc(ctx, siteId, opts)
}

func (m *ACLsClientMock) UpdateRule(ctx context.Context, siteId string, aclRuleId string, body ACLRuleUpdate) (*ACLRule, error) {
	return m.UpdateRuleFunc(ctx, siteId, aclRuleId, body)
}

func (m *ACLsClientMock) UpdateRuleOrdering(ctx context.Context, siteId string, body ACLRuleOrdering) (*ACLRuleOrdering, error) {
	return m.UpdateRuleOrderingFunc(ctx, siteId, body)
}
