// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import "context"

// ClientMock is a func-field test double implementing Client. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type ClientMock struct {
	AdoptDeviceFunc                      func(context.Context, string, DeviceAdoptionRequest) (*AdoptedDeviceDetails, error)
	CreateAclRuleFunc                    func(context.Context, string, ACLRuleUpdate) (*ACLRule, error)
	CreateDnsPolicyFunc                  func(context.Context, string, DNSPolicyCreateOrUpdate) (*DNSPolicy, error)
	CreateFirewallPolicyFunc             func(context.Context, string, FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error)
	CreateFirewallZoneFunc               func(context.Context, string, FirewallZoneCreateOrUpdate) (*FirewallZone, error)
	CreateNetworkFunc                    func(context.Context, string, NetworkCreateOrUpdate) (*NetworkDetails, error)
	CreateTrafficMatchingListFunc        func(context.Context, string, TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
	CreateVouchersFunc                   func(context.Context, string, HotspotVoucherCreationRequest) (*VoucherCreationResult, error)
	CreateWifiBroadcastFunc              func(context.Context, string, WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error)
	DeleteAclRuleFunc                    func(context.Context, string, string) error
	DeleteDnsPolicyFunc                  func(context.Context, string, string) error
	DeleteFirewallPolicyFunc             func(context.Context, string, string) error
	DeleteFirewallZoneFunc               func(context.Context, string, string) error
	DeleteNetworkFunc                    func(context.Context, string, string) error
	DeleteTrafficMatchingListFunc        func(context.Context, string, string) error
	DeleteVoucherFunc                    func(context.Context, string, string) (*VoucherDeletionResults, error)
	DeleteVouchersFunc                   func(context.Context, string, string) (*VoucherDeletionResults, error)
	DeleteWifiBroadcastFunc              func(context.Context, string, string) error
	ExecuteAdoptedDeviceActionFunc       func(context.Context, string, string, DeviceActionRequest) error
	ExecuteConnectedClientActionFunc     func(context.Context, string, string, ClientActionRequest) (*ClientActionResponse, error)
	ExecutePortActionFunc                func(context.Context, string, string, string, PortActionRequest) error
	GetAclRuleFunc                       func(context.Context, string, string) (*ACLRule, error)
	GetAclRuleOrderingFunc               func(context.Context, string) (*ACLRuleOrdering, error)
	GetAclRulePageFunc                   func(context.Context, string) ([]ACLRuleObject, error)
	GetAdoptedDeviceDetailsFunc          func(context.Context, string, string) (*AdoptedDeviceDetails, error)
	GetAdoptedDeviceLatestStatisticsFunc func(context.Context, string, string) (*LatestStatisticsForADevice, error)
	GetAdoptedDeviceOverviewPageFunc     func(context.Context, string) ([]AdoptedDeviceOverview, error)
	GetConnectedClientDetailsFunc        func(context.Context, string, string) (*ClientDetails, error)
	GetConnectedClientOverviewPageFunc   func(context.Context, string) ([]ClientOverview, error)
	GetCountriesFunc                     func(context.Context) ([]CountryDefinition, error)
	GetDeviceTagPageFunc                 func(context.Context, string) ([]DeviceTag, error)
	GetDnsPolicyFunc                     func(context.Context, string, string) (*DNSPolicy, error)
	GetDnsPolicyPageFunc                 func(context.Context, string) ([]DNSPolicy, error)
	GetDpiApplicationCategoriesFunc      func(context.Context) ([]DPICategory, error)
	GetDpiApplicationsFunc               func(context.Context) ([]DPIApplication, error)
	GetFirewallPoliciesFunc              func(context.Context, string) ([]FirewallPolicy, error)
	GetFirewallPolicyFunc                func(context.Context, string, string) (*FirewallPolicy, error)
	GetFirewallPolicyOrderingFunc        func(context.Context, string, string, string) (*FirewallPolicyOrdering, error)
	GetFirewallZoneFunc                  func(context.Context, string, string) (*FirewallZone, error)
	GetFirewallZonesFunc                 func(context.Context, string) ([]FirewallZone, error)
	GetInfoFunc                          func(context.Context) (*Info, error)
	GetNetworkDetailsFunc                func(context.Context, string, string) (*NetworkDetails, error)
	GetNetworkReferencesFunc             func(context.Context, string, string) (*NetworkReferences, error)
	GetNetworksOverviewPageFunc          func(context.Context, string) ([]NetworkOverview, error)
	GetPendingDevicePageFunc             func(context.Context) ([]DevicePendingAdoption, error)
	GetRadiusProfileOverviewPageFunc     func(context.Context, string) ([]RadiusProfileOverview, error)
	GetSiteToSiteVpnTunnelPageFunc       func(context.Context, string) ([]SiteToSiteVPNTunnelOverview, error)
	GetTrafficMatchingListFunc           func(context.Context, string, string) (*TrafficMatchingList, error)
	GetTrafficMatchingListsFunc          func(context.Context, string) ([]TrafficMatchingList, error)
	GetVoucherFunc                       func(context.Context, string, string) (*HotspotVoucherDetails, error)
	GetVouchersFunc                      func(context.Context, string) ([]HotspotVoucherDetails, error)
	GetVpnServerPageFunc                 func(context.Context, string) ([]VPNServerOverview, error)
	GetWansOverviewPageFunc              func(context.Context, string) ([]WANOverview, error)
	GetWifiBroadcastDetailsFunc          func(context.Context, string, string) (*WifiBroadcastDetails, error)
	GetWifiBroadcastPageFunc             func(context.Context, string) ([]WifiBroadcastOverview, error)
	ListSitesFunc                        func(context.Context) ([]SiteOverview, error)
	PatchFirewallPolicyFunc              func(context.Context, string, string, PatchFirewallPolicy) (*FirewallPolicy, error)
	RemoveDeviceFunc                     func(context.Context, string, string) error
	ResolveSiteIDFunc                    func(context.Context, string) (string, error)
	UpdateAclRuleFunc                    func(context.Context, string, string, ACLRuleUpdate) (*ACLRule, error)
	UpdateAclRuleOrderingFunc            func(context.Context, string, ACLRuleOrdering) (*ACLRuleOrdering, error)
	UpdateDnsPolicyFunc                  func(context.Context, string, string, DNSPolicyCreateOrUpdate) (*DNSPolicy, error)
	UpdateFirewallPolicyFunc             func(context.Context, string, string, FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error)
	UpdateFirewallPolicyOrderingFunc     func(context.Context, string, string, string, FirewallPolicyOrdering) (*FirewallPolicyOrdering, error)
	UpdateFirewallZoneFunc               func(context.Context, string, string, FirewallZoneCreateOrUpdate) (*FirewallZone, error)
	UpdateNetworkFunc                    func(context.Context, string, string, NetworkCreateOrUpdate) (*NetworkDetails, error)
	UpdateTrafficMatchingListFunc        func(context.Context, string, string, TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
	UpdateWifiBroadcastFunc              func(context.Context, string, string, WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error)
}

var _ Client = (*ClientMock)(nil)

func (m *ClientMock) AdoptDevice(ctx context.Context, siteId string, body DeviceAdoptionRequest) (*AdoptedDeviceDetails, error) {
	return m.AdoptDeviceFunc(ctx, siteId, body)
}

func (m *ClientMock) CreateAclRule(ctx context.Context, siteId string, body ACLRuleUpdate) (*ACLRule, error) {
	return m.CreateAclRuleFunc(ctx, siteId, body)
}

func (m *ClientMock) CreateDnsPolicy(ctx context.Context, siteId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	return m.CreateDnsPolicyFunc(ctx, siteId, body)
}

func (m *ClientMock) CreateFirewallPolicy(ctx context.Context, siteId string, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	return m.CreateFirewallPolicyFunc(ctx, siteId, body)
}

func (m *ClientMock) CreateFirewallZone(ctx context.Context, siteId string, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	return m.CreateFirewallZoneFunc(ctx, siteId, body)
}

func (m *ClientMock) CreateNetwork(ctx context.Context, siteId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	return m.CreateNetworkFunc(ctx, siteId, body)
}

func (m *ClientMock) CreateTrafficMatchingList(ctx context.Context, siteId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	return m.CreateTrafficMatchingListFunc(ctx, siteId, body)
}

func (m *ClientMock) CreateVouchers(ctx context.Context, siteId string, body HotspotVoucherCreationRequest) (*VoucherCreationResult, error) {
	return m.CreateVouchersFunc(ctx, siteId, body)
}

func (m *ClientMock) CreateWifiBroadcast(ctx context.Context, siteId string, body WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error) {
	return m.CreateWifiBroadcastFunc(ctx, siteId, body)
}

func (m *ClientMock) DeleteAclRule(ctx context.Context, siteId string, aclRuleId string) error {
	return m.DeleteAclRuleFunc(ctx, siteId, aclRuleId)
}

func (m *ClientMock) DeleteDnsPolicy(ctx context.Context, siteId string, dnsPolicyId string) error {
	return m.DeleteDnsPolicyFunc(ctx, siteId, dnsPolicyId)
}

func (m *ClientMock) DeleteFirewallPolicy(ctx context.Context, siteId string, firewallPolicyId string) error {
	return m.DeleteFirewallPolicyFunc(ctx, siteId, firewallPolicyId)
}

func (m *ClientMock) DeleteFirewallZone(ctx context.Context, siteId string, firewallZoneId string) error {
	return m.DeleteFirewallZoneFunc(ctx, siteId, firewallZoneId)
}

func (m *ClientMock) DeleteNetwork(ctx context.Context, siteId string, networkId string) error {
	return m.DeleteNetworkFunc(ctx, siteId, networkId)
}

func (m *ClientMock) DeleteTrafficMatchingList(ctx context.Context, siteId string, trafficMatchingListId string) error {
	return m.DeleteTrafficMatchingListFunc(ctx, siteId, trafficMatchingListId)
}

func (m *ClientMock) DeleteVoucher(ctx context.Context, siteId string, voucherId string) (*VoucherDeletionResults, error) {
	return m.DeleteVoucherFunc(ctx, siteId, voucherId)
}

func (m *ClientMock) DeleteVouchers(ctx context.Context, siteId string, filter string) (*VoucherDeletionResults, error) {
	return m.DeleteVouchersFunc(ctx, siteId, filter)
}

func (m *ClientMock) DeleteWifiBroadcast(ctx context.Context, siteId string, wifiBroadcastId string) error {
	return m.DeleteWifiBroadcastFunc(ctx, siteId, wifiBroadcastId)
}

func (m *ClientMock) ExecuteAdoptedDeviceAction(ctx context.Context, siteId string, deviceId string, body DeviceActionRequest) error {
	return m.ExecuteAdoptedDeviceActionFunc(ctx, siteId, deviceId, body)
}

func (m *ClientMock) ExecuteConnectedClientAction(ctx context.Context, siteId string, clientId string, body ClientActionRequest) (*ClientActionResponse, error) {
	return m.ExecuteConnectedClientActionFunc(ctx, siteId, clientId, body)
}

func (m *ClientMock) ExecutePortAction(ctx context.Context, siteId string, deviceId string, portIdx string, body PortActionRequest) error {
	return m.ExecutePortActionFunc(ctx, siteId, deviceId, portIdx, body)
}

func (m *ClientMock) GetAclRule(ctx context.Context, siteId string, aclRuleId string) (*ACLRule, error) {
	return m.GetAclRuleFunc(ctx, siteId, aclRuleId)
}

func (m *ClientMock) GetAclRuleOrdering(ctx context.Context, siteId string) (*ACLRuleOrdering, error) {
	return m.GetAclRuleOrderingFunc(ctx, siteId)
}

func (m *ClientMock) GetAclRulePage(ctx context.Context, siteId string) ([]ACLRuleObject, error) {
	return m.GetAclRulePageFunc(ctx, siteId)
}

func (m *ClientMock) GetAdoptedDeviceDetails(ctx context.Context, siteId string, deviceId string) (*AdoptedDeviceDetails, error) {
	return m.GetAdoptedDeviceDetailsFunc(ctx, siteId, deviceId)
}

func (m *ClientMock) GetAdoptedDeviceLatestStatistics(ctx context.Context, siteId string, deviceId string) (*LatestStatisticsForADevice, error) {
	return m.GetAdoptedDeviceLatestStatisticsFunc(ctx, siteId, deviceId)
}

func (m *ClientMock) GetAdoptedDeviceOverviewPage(ctx context.Context, siteId string) ([]AdoptedDeviceOverview, error) {
	return m.GetAdoptedDeviceOverviewPageFunc(ctx, siteId)
}

func (m *ClientMock) GetConnectedClientDetails(ctx context.Context, siteId string, clientId string) (*ClientDetails, error) {
	return m.GetConnectedClientDetailsFunc(ctx, siteId, clientId)
}

func (m *ClientMock) GetConnectedClientOverviewPage(ctx context.Context, siteId string) ([]ClientOverview, error) {
	return m.GetConnectedClientOverviewPageFunc(ctx, siteId)
}

func (m *ClientMock) GetCountries(ctx context.Context) ([]CountryDefinition, error) {
	return m.GetCountriesFunc(ctx)
}

func (m *ClientMock) GetDeviceTagPage(ctx context.Context, siteId string) ([]DeviceTag, error) {
	return m.GetDeviceTagPageFunc(ctx, siteId)
}

func (m *ClientMock) GetDnsPolicy(ctx context.Context, siteId string, dnsPolicyId string) (*DNSPolicy, error) {
	return m.GetDnsPolicyFunc(ctx, siteId, dnsPolicyId)
}

func (m *ClientMock) GetDnsPolicyPage(ctx context.Context, siteId string) ([]DNSPolicy, error) {
	return m.GetDnsPolicyPageFunc(ctx, siteId)
}

func (m *ClientMock) GetDpiApplicationCategories(ctx context.Context) ([]DPICategory, error) {
	return m.GetDpiApplicationCategoriesFunc(ctx)
}

func (m *ClientMock) GetDpiApplications(ctx context.Context) ([]DPIApplication, error) {
	return m.GetDpiApplicationsFunc(ctx)
}

func (m *ClientMock) GetFirewallPolicies(ctx context.Context, siteId string) ([]FirewallPolicy, error) {
	return m.GetFirewallPoliciesFunc(ctx, siteId)
}

func (m *ClientMock) GetFirewallPolicy(ctx context.Context, siteId string, firewallPolicyId string) (*FirewallPolicy, error) {
	return m.GetFirewallPolicyFunc(ctx, siteId, firewallPolicyId)
}

func (m *ClientMock) GetFirewallPolicyOrdering(ctx context.Context, siteId string, sourceFirewallZoneId string, destinationFirewallZoneId string) (*FirewallPolicyOrdering, error) {
	return m.GetFirewallPolicyOrderingFunc(ctx, siteId, sourceFirewallZoneId, destinationFirewallZoneId)
}

func (m *ClientMock) GetFirewallZone(ctx context.Context, siteId string, firewallZoneId string) (*FirewallZone, error) {
	return m.GetFirewallZoneFunc(ctx, siteId, firewallZoneId)
}

func (m *ClientMock) GetFirewallZones(ctx context.Context, siteId string) ([]FirewallZone, error) {
	return m.GetFirewallZonesFunc(ctx, siteId)
}

func (m *ClientMock) GetInfo(ctx context.Context) (*Info, error) {
	return m.GetInfoFunc(ctx)
}

func (m *ClientMock) GetNetworkDetails(ctx context.Context, siteId string, networkId string) (*NetworkDetails, error) {
	return m.GetNetworkDetailsFunc(ctx, siteId, networkId)
}

func (m *ClientMock) GetNetworkReferences(ctx context.Context, siteId string, networkId string) (*NetworkReferences, error) {
	return m.GetNetworkReferencesFunc(ctx, siteId, networkId)
}

func (m *ClientMock) GetNetworksOverviewPage(ctx context.Context, siteId string) ([]NetworkOverview, error) {
	return m.GetNetworksOverviewPageFunc(ctx, siteId)
}

func (m *ClientMock) GetPendingDevicePage(ctx context.Context) ([]DevicePendingAdoption, error) {
	return m.GetPendingDevicePageFunc(ctx)
}

func (m *ClientMock) GetRadiusProfileOverviewPage(ctx context.Context, siteId string) ([]RadiusProfileOverview, error) {
	return m.GetRadiusProfileOverviewPageFunc(ctx, siteId)
}

func (m *ClientMock) GetSiteToSiteVpnTunnelPage(ctx context.Context, siteId string) ([]SiteToSiteVPNTunnelOverview, error) {
	return m.GetSiteToSiteVpnTunnelPageFunc(ctx, siteId)
}

func (m *ClientMock) GetTrafficMatchingList(ctx context.Context, siteId string, trafficMatchingListId string) (*TrafficMatchingList, error) {
	return m.GetTrafficMatchingListFunc(ctx, siteId, trafficMatchingListId)
}

func (m *ClientMock) GetTrafficMatchingLists(ctx context.Context, siteId string) ([]TrafficMatchingList, error) {
	return m.GetTrafficMatchingListsFunc(ctx, siteId)
}

func (m *ClientMock) GetVoucher(ctx context.Context, siteId string, voucherId string) (*HotspotVoucherDetails, error) {
	return m.GetVoucherFunc(ctx, siteId, voucherId)
}

func (m *ClientMock) GetVouchers(ctx context.Context, siteId string) ([]HotspotVoucherDetails, error) {
	return m.GetVouchersFunc(ctx, siteId)
}

func (m *ClientMock) GetVpnServerPage(ctx context.Context, siteId string) ([]VPNServerOverview, error) {
	return m.GetVpnServerPageFunc(ctx, siteId)
}

func (m *ClientMock) GetWansOverviewPage(ctx context.Context, siteId string) ([]WANOverview, error) {
	return m.GetWansOverviewPageFunc(ctx, siteId)
}

func (m *ClientMock) GetWifiBroadcastDetails(ctx context.Context, siteId string, wifiBroadcastId string) (*WifiBroadcastDetails, error) {
	return m.GetWifiBroadcastDetailsFunc(ctx, siteId, wifiBroadcastId)
}

func (m *ClientMock) GetWifiBroadcastPage(ctx context.Context, siteId string) ([]WifiBroadcastOverview, error) {
	return m.GetWifiBroadcastPageFunc(ctx, siteId)
}

func (m *ClientMock) ListSites(ctx context.Context) ([]SiteOverview, error) {
	return m.ListSitesFunc(ctx)
}

func (m *ClientMock) PatchFirewallPolicy(ctx context.Context, siteId string, firewallPolicyId string, body PatchFirewallPolicy) (*FirewallPolicy, error) {
	return m.PatchFirewallPolicyFunc(ctx, siteId, firewallPolicyId, body)
}

func (m *ClientMock) RemoveDevice(ctx context.Context, siteId string, deviceId string) error {
	return m.RemoveDeviceFunc(ctx, siteId, deviceId)
}

func (m *ClientMock) ResolveSiteID(ctx context.Context, name string) (string, error) {
	return m.ResolveSiteIDFunc(ctx, name)
}

func (m *ClientMock) UpdateAclRule(ctx context.Context, siteId string, aclRuleId string, body ACLRuleUpdate) (*ACLRule, error) {
	return m.UpdateAclRuleFunc(ctx, siteId, aclRuleId, body)
}

func (m *ClientMock) UpdateAclRuleOrdering(ctx context.Context, siteId string, body ACLRuleOrdering) (*ACLRuleOrdering, error) {
	return m.UpdateAclRuleOrderingFunc(ctx, siteId, body)
}

func (m *ClientMock) UpdateDnsPolicy(ctx context.Context, siteId string, dnsPolicyId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	return m.UpdateDnsPolicyFunc(ctx, siteId, dnsPolicyId, body)
}

func (m *ClientMock) UpdateFirewallPolicy(ctx context.Context, siteId string, firewallPolicyId string, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	return m.UpdateFirewallPolicyFunc(ctx, siteId, firewallPolicyId, body)
}

func (m *ClientMock) UpdateFirewallPolicyOrdering(ctx context.Context, siteId string, sourceFirewallZoneId string, destinationFirewallZoneId string, body FirewallPolicyOrdering) (*FirewallPolicyOrdering, error) {
	return m.UpdateFirewallPolicyOrderingFunc(ctx, siteId, sourceFirewallZoneId, destinationFirewallZoneId, body)
}

func (m *ClientMock) UpdateFirewallZone(ctx context.Context, siteId string, firewallZoneId string, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	return m.UpdateFirewallZoneFunc(ctx, siteId, firewallZoneId, body)
}

func (m *ClientMock) UpdateNetwork(ctx context.Context, siteId string, networkId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	return m.UpdateNetworkFunc(ctx, siteId, networkId, body)
}

func (m *ClientMock) UpdateTrafficMatchingList(ctx context.Context, siteId string, trafficMatchingListId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	return m.UpdateTrafficMatchingListFunc(ctx, siteId, trafficMatchingListId, body)
}

func (m *ClientMock) UpdateWifiBroadcast(ctx context.Context, siteId string, wifiBroadcastId string, body WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error) {
	return m.UpdateWifiBroadcastFunc(ctx, siteId, wifiBroadcastId, body)
}
