// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// ClientsClient is the Clients resource group of the Official UniFi OpenAPI surface.
type ClientsClient interface {
	// ExecuteConnectedAction maps to POST /v1/sites/%s/clients/%s/actions on the Official API.
	ExecuteConnectedAction(ctx context.Context, siteId string, clientId string, body ClientActionRequest) (*ClientActionResponse, error)
	// GetConnected maps to GET /v1/sites/%s/clients/%s on the Official API.
	GetConnected(ctx context.Context, siteId string, clientId string) (*ClientDetails, error)
	// ListConnected maps to GET /v1/sites/%s/clients on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
	ListConnected(ctx context.Context, siteId string, opts ...ListOption) ([]ClientOverview, error)
}

// clientsClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type clientsClient struct{ *apiClient }

var _ ClientsClient = clientsClient{}

// Clients returns the Clients resource group.
func (c *apiClient) Clients() ClientsClient {
	return clientsClient{c}
}

// ExecuteConnectedAction maps to POST /v1/sites/%s/clients/%s/actions on the Official API.
func (c clientsClient) ExecuteConnectedAction(ctx context.Context, siteId string, clientId string, body ClientActionRequest) (*ClientActionResponse, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ClientActionResponse
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/clients/%s/actions", url.PathEscape(siteId), url.PathEscape(clientId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed ExecuteConnectedAction: %w", err)
	}
	return &out, nil
}

// GetConnected maps to GET /v1/sites/%s/clients/%s on the Official API.
func (c clientsClient) GetConnected(ctx context.Context, siteId string, clientId string) (*ClientDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ClientDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/clients/%s", url.PathEscape(siteId), url.PathEscape(clientId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetConnected: %w", err)
	}
	return &out, nil
}

// ListConnected maps to GET /v1/sites/%s/clients on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
func (c clientsClient) ListConnected(ctx context.Context, siteId string, opts ...ListOption) ([]ClientOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []ClientOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/clients", url.PathEscape(siteId))), &out, opts...); err != nil {
		return nil, fmt.Errorf("failed ListConnected: %w", err)
	}
	return out, nil
}

// ClientsClientMock is a func-field test double implementing ClientsClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type ClientsClientMock struct {
	ExecuteConnectedActionFunc func(context.Context, string, string, ClientActionRequest) (*ClientActionResponse, error)
	GetConnectedFunc           func(context.Context, string, string) (*ClientDetails, error)
	ListConnectedFunc          func(context.Context, string, ...ListOption) ([]ClientOverview, error)
}

var _ ClientsClient = (*ClientsClientMock)(nil)

func (m *ClientsClientMock) ExecuteConnectedAction(ctx context.Context, siteId string, clientId string, body ClientActionRequest) (*ClientActionResponse, error) {
	return m.ExecuteConnectedActionFunc(ctx, siteId, clientId, body)
}

func (m *ClientsClientMock) GetConnected(ctx context.Context, siteId string, clientId string) (*ClientDetails, error) {
	return m.GetConnectedFunc(ctx, siteId, clientId)
}

func (m *ClientsClientMock) ListConnected(ctx context.Context, siteId string, opts ...ListOption) ([]ClientOverview, error) {
	return m.ListConnectedFunc(ctx, siteId, opts...)
}
