// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

// Client is the Official UniFi OpenAPI (integration/v1) surface, exposed as one
// fluent accessor per resource group (e.g. Firewall().CreatePolicy(ctx, ...)).
type Client interface {
	// ACL returns the ACL resource group.
	ACL() ACLClient
	// Clients returns the Clients resource group.
	Clients() ClientsClient
	// DNSPolicy returns the DNSPolicy resource group.
	DNSPolicy() DNSPolicyClient
	// Devices returns the Devices resource group.
	Devices() DevicesClient
	// Firewall returns the Firewall resource group.
	Firewall() FirewallClient
	// Hotspot returns the Hotspot resource group.
	Hotspot() HotspotClient
	// Info returns the Info resource group.
	Info() InfoClient
	// Networks returns the Networks resource group.
	Networks() NetworksClient
	// Sites returns the Sites resource group.
	Sites() SitesClient
	// Supporting returns the Supporting resource group.
	Supporting() SupportingClient
	// TrafficMatching returns the TrafficMatching resource group.
	TrafficMatching() TrafficMatchingClient
	// WifiBroadcasts returns the WifiBroadcasts resource group.
	WifiBroadcasts() WifiBroadcastsClient
}

var _ Client = (*apiClient)(nil)

// ClientMock is a func-field test double implementing Client; each accessor
// returns a per-group mock. A nil field panics on call.
type ClientMock struct {
	ACLFunc             func() ACLClient
	ClientsFunc         func() ClientsClient
	DNSPolicyFunc       func() DNSPolicyClient
	DevicesFunc         func() DevicesClient
	FirewallFunc        func() FirewallClient
	HotspotFunc         func() HotspotClient
	InfoFunc            func() InfoClient
	NetworksFunc        func() NetworksClient
	SitesFunc           func() SitesClient
	SupportingFunc      func() SupportingClient
	TrafficMatchingFunc func() TrafficMatchingClient
	WifiBroadcastsFunc  func() WifiBroadcastsClient
}

var _ Client = (*ClientMock)(nil)

func (m *ClientMock) ACL() ACLClient {
	return m.ACLFunc()
}

func (m *ClientMock) Clients() ClientsClient {
	return m.ClientsFunc()
}

func (m *ClientMock) DNSPolicy() DNSPolicyClient {
	return m.DNSPolicyFunc()
}

func (m *ClientMock) Devices() DevicesClient {
	return m.DevicesFunc()
}

func (m *ClientMock) Firewall() FirewallClient {
	return m.FirewallFunc()
}

func (m *ClientMock) Hotspot() HotspotClient {
	return m.HotspotFunc()
}

func (m *ClientMock) Info() InfoClient {
	return m.InfoFunc()
}

func (m *ClientMock) Networks() NetworksClient {
	return m.NetworksFunc()
}

func (m *ClientMock) Sites() SitesClient {
	return m.SitesFunc()
}

func (m *ClientMock) Supporting() SupportingClient {
	return m.SupportingFunc()
}

func (m *ClientMock) TrafficMatching() TrafficMatchingClient {
	return m.TrafficMatchingFunc()
}

func (m *ClientMock) WifiBroadcasts() WifiBroadcastsClient {
	return m.WifiBroadcastsFunc()
}
