// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"iter"
	"net/url"
)

// DevicesClient is the Devices resource group of the Official UniFi OpenAPI surface.
type DevicesClient interface {
	// Adopt maps to POST /v1/sites/%s/devices on the Official API.
	Adopt(ctx context.Context, siteId string, body DeviceAdoptionRequest) (*AdoptedDeviceDetails, error)
	// ExecuteAdoptedAction maps to POST /v1/sites/%s/devices/%s/actions on the Official API.
	ExecuteAdoptedAction(ctx context.Context, siteId string, deviceId string, body DeviceActionRequest) error
	// ExecutePortAction maps to POST /v1/sites/%s/devices/%s/interfaces/ports/%s/actions on the Official API.
	ExecutePortAction(ctx context.Context, siteId string, deviceId string, portIdx string, body PortActionRequest) error
	// GetAdopted maps to GET /v1/sites/%s/devices/%s on the Official API.
	GetAdopted(ctx context.Context, siteId string, deviceId string) (*AdoptedDeviceDetails, error)
	// GetAdoptedLatestStatistics maps to GET /v1/sites/%s/devices/%s/statistics/latest on the Official API.
	GetAdoptedLatestStatistics(ctx context.Context, siteId string, deviceId string) (*LatestStatisticsForADevice, error)
	// ListAdoptedAll lazily drains every item from GET /v1/sites/%s/devices, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListAdoptedAll(ctx context.Context, siteId string, filter string) iter.Seq2[AdoptedDeviceOverview, error]
	// ListAdoptedPage returns one page from GET /v1/sites/%s/devices; nil opts fetches the first page at the default size.
	ListAdoptedPage(ctx context.Context, siteId string, opts *ListOptions) (Page[AdoptedDeviceOverview], error)
	// ListPendingAll lazily drains every item from GET /v1/pending-devices, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListPendingAll(ctx context.Context, filter string) iter.Seq2[DevicePendingAdoption, error]
	// ListPendingPage returns one page from GET /v1/pending-devices; nil opts fetches the first page at the default size.
	ListPendingPage(ctx context.Context, opts *ListOptions) (Page[DevicePendingAdoption], error)
	// Remove maps to DELETE /v1/sites/%s/devices/%s on the Official API.
	Remove(ctx context.Context, siteId string, deviceId string) error
}

// devicesClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type devicesClient struct{ *apiClient }

var _ DevicesClient = devicesClient{}

// Devices returns the Devices resource group.
func (c *apiClient) Devices() DevicesClient {
	return devicesClient{c}
}

// Adopt maps to POST /v1/sites/%s/devices on the Official API.
func (c devicesClient) Adopt(ctx context.Context, siteId string, body DeviceAdoptionRequest) (*AdoptedDeviceDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out AdoptedDeviceDetails
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Adopt: %w", err)
	}
	return &out, nil
}

// ExecuteAdoptedAction maps to POST /v1/sites/%s/devices/%s/actions on the Official API.
func (c devicesClient) ExecuteAdoptedAction(ctx context.Context, siteId string, deviceId string, body DeviceActionRequest) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/actions", url.PathEscape(siteId), url.PathEscape(deviceId))), body, nil); err != nil {
		return fmt.Errorf("failed ExecuteAdoptedAction: %w", err)
	}
	return nil
}

// ExecutePortAction maps to POST /v1/sites/%s/devices/%s/interfaces/ports/%s/actions on the Official API.
func (c devicesClient) ExecutePortAction(ctx context.Context, siteId string, deviceId string, portIdx string, body PortActionRequest) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/interfaces/ports/%s/actions", url.PathEscape(siteId), url.PathEscape(deviceId), url.PathEscape(portIdx))), body, nil); err != nil {
		return fmt.Errorf("failed ExecutePortAction: %w", err)
	}
	return nil
}

// GetAdopted maps to GET /v1/sites/%s/devices/%s on the Official API.
func (c devicesClient) GetAdopted(ctx context.Context, siteId string, deviceId string) (*AdoptedDeviceDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out AdoptedDeviceDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s", url.PathEscape(siteId), url.PathEscape(deviceId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetAdopted: %w", err)
	}
	return &out, nil
}

// GetAdoptedLatestStatistics maps to GET /v1/sites/%s/devices/%s/statistics/latest on the Official API.
func (c devicesClient) GetAdoptedLatestStatistics(ctx context.Context, siteId string, deviceId string) (*LatestStatisticsForADevice, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out LatestStatisticsForADevice
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/statistics/latest", url.PathEscape(siteId), url.PathEscape(deviceId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetAdoptedLatestStatistics: %w", err)
	}
	return &out, nil
}

// ListAdoptedAll lazily drains every item from GET /v1/sites/%s/devices, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c devicesClient) ListAdoptedAll(ctx context.Context, siteId string, filter string) iter.Seq2[AdoptedDeviceOverview, error] {
	return listSeq[AdoptedDeviceOverview](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/devices", url.PathEscape(siteId))), filter)
}

// ListAdoptedPage returns one page from GET /v1/sites/%s/devices; nil opts fetches the first page at the default size.
func (c devicesClient) ListAdoptedPage(ctx context.Context, siteId string, opts *ListOptions) (Page[AdoptedDeviceOverview], error) {
	if err := c.check(ctx); err != nil {
		return Page[AdoptedDeviceOverview]{}, err
	}
	p, err := listPage[AdoptedDeviceOverview](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/devices", url.PathEscape(siteId))), opts)
	if err != nil {
		return Page[AdoptedDeviceOverview]{}, fmt.Errorf("failed ListAdoptedPage: %w", err)
	}
	return p, nil
}

// ListPendingAll lazily drains every item from GET /v1/pending-devices, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c devicesClient) ListPendingAll(ctx context.Context, filter string) iter.Seq2[DevicePendingAdoption, error] {
	return listSeq[DevicePendingAdoption](ctx, c.apiClient, c.path("/pending-devices"), filter)
}

// ListPendingPage returns one page from GET /v1/pending-devices; nil opts fetches the first page at the default size.
func (c devicesClient) ListPendingPage(ctx context.Context, opts *ListOptions) (Page[DevicePendingAdoption], error) {
	if err := c.check(ctx); err != nil {
		return Page[DevicePendingAdoption]{}, err
	}
	p, err := listPage[DevicePendingAdoption](ctx, c.doer, c.path("/pending-devices"), opts)
	if err != nil {
		return Page[DevicePendingAdoption]{}, fmt.Errorf("failed ListPendingPage: %w", err)
	}
	return p, nil
}

// Remove maps to DELETE /v1/sites/%s/devices/%s on the Official API.
func (c devicesClient) Remove(ctx context.Context, siteId string, deviceId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s", url.PathEscape(siteId), url.PathEscape(deviceId))), nil, nil); err != nil {
		return fmt.Errorf("failed Remove: %w", err)
	}
	return nil
}

// DevicesClientMock is a func-field test double implementing DevicesClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type DevicesClientMock struct {
	AdoptFunc                      func(context.Context, string, DeviceAdoptionRequest) (*AdoptedDeviceDetails, error)
	ExecuteAdoptedActionFunc       func(context.Context, string, string, DeviceActionRequest) error
	ExecutePortActionFunc          func(context.Context, string, string, string, PortActionRequest) error
	GetAdoptedFunc                 func(context.Context, string, string) (*AdoptedDeviceDetails, error)
	GetAdoptedLatestStatisticsFunc func(context.Context, string, string) (*LatestStatisticsForADevice, error)
	ListAdoptedAllFunc             func(context.Context, string, string) iter.Seq2[AdoptedDeviceOverview, error]
	ListAdoptedPageFunc            func(context.Context, string, *ListOptions) (Page[AdoptedDeviceOverview], error)
	ListPendingAllFunc             func(context.Context, string) iter.Seq2[DevicePendingAdoption, error]
	ListPendingPageFunc            func(context.Context, *ListOptions) (Page[DevicePendingAdoption], error)
	RemoveFunc                     func(context.Context, string, string) error
}

var _ DevicesClient = (*DevicesClientMock)(nil)

func (m *DevicesClientMock) Adopt(ctx context.Context, siteId string, body DeviceAdoptionRequest) (*AdoptedDeviceDetails, error) {
	return m.AdoptFunc(ctx, siteId, body)
}

func (m *DevicesClientMock) ExecuteAdoptedAction(ctx context.Context, siteId string, deviceId string, body DeviceActionRequest) error {
	return m.ExecuteAdoptedActionFunc(ctx, siteId, deviceId, body)
}

func (m *DevicesClientMock) ExecutePortAction(ctx context.Context, siteId string, deviceId string, portIdx string, body PortActionRequest) error {
	return m.ExecutePortActionFunc(ctx, siteId, deviceId, portIdx, body)
}

func (m *DevicesClientMock) GetAdopted(ctx context.Context, siteId string, deviceId string) (*AdoptedDeviceDetails, error) {
	return m.GetAdoptedFunc(ctx, siteId, deviceId)
}

func (m *DevicesClientMock) GetAdoptedLatestStatistics(ctx context.Context, siteId string, deviceId string) (*LatestStatisticsForADevice, error) {
	return m.GetAdoptedLatestStatisticsFunc(ctx, siteId, deviceId)
}

func (m *DevicesClientMock) ListAdoptedAll(ctx context.Context, siteId string, filter string) iter.Seq2[AdoptedDeviceOverview, error] {
	return m.ListAdoptedAllFunc(ctx, siteId, filter)
}

func (m *DevicesClientMock) ListAdoptedPage(ctx context.Context, siteId string, opts *ListOptions) (Page[AdoptedDeviceOverview], error) {
	return m.ListAdoptedPageFunc(ctx, siteId, opts)
}

func (m *DevicesClientMock) ListPendingAll(ctx context.Context, filter string) iter.Seq2[DevicePendingAdoption, error] {
	return m.ListPendingAllFunc(ctx, filter)
}

func (m *DevicesClientMock) ListPendingPage(ctx context.Context, opts *ListOptions) (Page[DevicePendingAdoption], error) {
	return m.ListPendingPageFunc(ctx, opts)
}

func (m *DevicesClientMock) Remove(ctx context.Context, siteId string, deviceId string) error {
	return m.RemoveFunc(ctx, siteId, deviceId)
}
