// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// DevicesClient is the Devices resource group of the Official UniFi OpenAPI surface.
type DevicesClient interface {
	// Adopt maps to POST /v1/sites/%s/devices on the Official API.
	Adopt(ctx context.Context, siteId string, body DeviceAdoptionRequest) (*AdoptedDeviceDetails, error)
	// ExecuteAdoptedAction maps to POST /v1/sites/%s/devices/%s/actions on the Official API.
	ExecuteAdoptedAction(ctx context.Context, siteId string, deviceId string, body DeviceActionRequest) error
	// ExecutePortAction maps to POST /v1/sites/%s/devices/%s/interfaces/ports/%s/actions on the Official API.
	ExecutePortAction(ctx context.Context, siteId string, deviceId string, portIdx string, body PortActionRequest) error
	// GetAdopted maps to GET /v1/sites/%s/devices/%s on the Official API.
	GetAdopted(ctx context.Context, siteId string, deviceId string) (*AdoptedDeviceDetails, error)
	// GetAdoptedLatestStatistics maps to GET /v1/sites/%s/devices/%s/statistics/latest on the Official API.
	GetAdoptedLatestStatistics(ctx context.Context, siteId string, deviceId string) (*LatestStatisticsForADevice, error)
	// ListAdopted maps to GET /v1/sites/%s/devices on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
	ListAdopted(ctx context.Context, siteId string, opts ...ListOption) ([]AdoptedDeviceOverview, error)
	// ListPending maps to GET /v1/pending-devices on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
	ListPending(ctx context.Context, opts ...ListOption) ([]DevicePendingAdoption, error)
	// Remove maps to DELETE /v1/sites/%s/devices/%s on the Official API.
	Remove(ctx context.Context, siteId string, deviceId string) error
}

// devicesClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type devicesClient struct{ *apiClient }

var _ DevicesClient = devicesClient{}

// Devices returns the Devices resource group.
func (c *apiClient) Devices() DevicesClient {
	return devicesClient{c}
}

// Adopt maps to POST /v1/sites/%s/devices on the Official API.
func (c devicesClient) Adopt(ctx context.Context, siteId string, body DeviceAdoptionRequest) (*AdoptedDeviceDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out AdoptedDeviceDetails
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Adopt: %w", err)
	}
	return &out, nil
}

// ExecuteAdoptedAction maps to POST /v1/sites/%s/devices/%s/actions on the Official API.
func (c devicesClient) ExecuteAdoptedAction(ctx context.Context, siteId string, deviceId string, body DeviceActionRequest) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/actions", url.PathEscape(siteId), url.PathEscape(deviceId))), body, nil); err != nil {
		return fmt.Errorf("failed ExecuteAdoptedAction: %w", err)
	}
	return nil
}

// ExecutePortAction maps to POST /v1/sites/%s/devices/%s/interfaces/ports/%s/actions on the Official API.
func (c devicesClient) ExecutePortAction(ctx context.Context, siteId string, deviceId string, portIdx string, body PortActionRequest) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/interfaces/ports/%s/actions", url.PathEscape(siteId), url.PathEscape(deviceId), url.PathEscape(portIdx))), body, nil); err != nil {
		return fmt.Errorf("failed ExecutePortAction: %w", err)
	}
	return nil
}

// GetAdopted maps to GET /v1/sites/%s/devices/%s on the Official API.
func (c devicesClient) GetAdopted(ctx context.Context, siteId string, deviceId string) (*AdoptedDeviceDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out AdoptedDeviceDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s", url.PathEscape(siteId), url.PathEscape(deviceId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetAdopted: %w", err)
	}
	return &out, nil
}

// GetAdoptedLatestStatistics maps to GET /v1/sites/%s/devices/%s/statistics/latest on the Official API.
func (c devicesClient) GetAdoptedLatestStatistics(ctx context.Context, siteId string, deviceId string) (*LatestStatisticsForADevice, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out LatestStatisticsForADevice
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/statistics/latest", url.PathEscape(siteId), url.PathEscape(deviceId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetAdoptedLatestStatistics: %w", err)
	}
	return &out, nil
}

// ListAdopted maps to GET /v1/sites/%s/devices on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
func (c devicesClient) ListAdopted(ctx context.Context, siteId string, opts ...ListOption) ([]AdoptedDeviceOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []AdoptedDeviceOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/devices", url.PathEscape(siteId))), &out, opts...); err != nil {
		return nil, fmt.Errorf("failed ListAdopted: %w", err)
	}
	return out, nil
}

// ListPending maps to GET /v1/pending-devices on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
func (c devicesClient) ListPending(ctx context.Context, opts ...ListOption) ([]DevicePendingAdoption, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []DevicePendingAdoption
	if err := listAll(ctx, c.doer, c.path("/pending-devices"), &out, opts...); err != nil {
		return nil, fmt.Errorf("failed ListPending: %w", err)
	}
	return out, nil
}

// Remove maps to DELETE /v1/sites/%s/devices/%s on the Official API.
func (c devicesClient) Remove(ctx context.Context, siteId string, deviceId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s", url.PathEscape(siteId), url.PathEscape(deviceId))), nil, nil); err != nil {
		return fmt.Errorf("failed Remove: %w", err)
	}
	return nil
}

// DevicesClientMock is a func-field test double implementing DevicesClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type DevicesClientMock struct {
	AdoptFunc                      func(context.Context, string, DeviceAdoptionRequest) (*AdoptedDeviceDetails, error)
	ExecuteAdoptedActionFunc       func(context.Context, string, string, DeviceActionRequest) error
	ExecutePortActionFunc          func(context.Context, string, string, string, PortActionRequest) error
	GetAdoptedFunc                 func(context.Context, string, string) (*AdoptedDeviceDetails, error)
	GetAdoptedLatestStatisticsFunc func(context.Context, string, string) (*LatestStatisticsForADevice, error)
	ListAdoptedFunc                func(context.Context, string, ...ListOption) ([]AdoptedDeviceOverview, error)
	ListPendingFunc                func(context.Context, ...ListOption) ([]DevicePendingAdoption, error)
	RemoveFunc                     func(context.Context, string, string) error
}

var _ DevicesClient = (*DevicesClientMock)(nil)

func (m *DevicesClientMock) Adopt(ctx context.Context, siteId string, body DeviceAdoptionRequest) (*AdoptedDeviceDetails, error) {
	return m.AdoptFunc(ctx, siteId, body)
}

func (m *DevicesClientMock) ExecuteAdoptedAction(ctx context.Context, siteId string, deviceId string, body DeviceActionRequest) error {
	return m.ExecuteAdoptedActionFunc(ctx, siteId, deviceId, body)
}

func (m *DevicesClientMock) ExecutePortAction(ctx context.Context, siteId string, deviceId string, portIdx string, body PortActionRequest) error {
	return m.ExecutePortActionFunc(ctx, siteId, deviceId, portIdx, body)
}

func (m *DevicesClientMock) GetAdopted(ctx context.Context, siteId string, deviceId string) (*AdoptedDeviceDetails, error) {
	return m.GetAdoptedFunc(ctx, siteId, deviceId)
}

func (m *DevicesClientMock) GetAdoptedLatestStatistics(ctx context.Context, siteId string, deviceId string) (*LatestStatisticsForADevice, error) {
	return m.GetAdoptedLatestStatisticsFunc(ctx, siteId, deviceId)
}

func (m *DevicesClientMock) ListAdopted(ctx context.Context, siteId string, opts ...ListOption) ([]AdoptedDeviceOverview, error) {
	return m.ListAdoptedFunc(ctx, siteId, opts...)
}

func (m *DevicesClientMock) ListPending(ctx context.Context, opts ...ListOption) ([]DevicePendingAdoption, error) {
	return m.ListPendingFunc(ctx, opts...)
}

func (m *DevicesClientMock) Remove(ctx context.Context, siteId string, deviceId string) error {
	return m.RemoveFunc(ctx, siteId, deviceId)
}
