// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// DevicesClient is the Devices resource group of the Official UniFi OpenAPI surface.
type DevicesClient interface {
	// Adopt maps to POST /v1/sites/%s/devices on the Official API.
	Adopt(ctx context.Context, siteId string, body DeviceAdoptionRequest) (*AdoptedDeviceDetails, error)
	// ExecuteAdoptedAction maps to POST /v1/sites/%s/devices/%s/actions on the Official API.
	ExecuteAdoptedAction(ctx context.Context, siteId string, deviceId string, body DeviceActionRequest) error
	// ExecutePortAction maps to POST /v1/sites/%s/devices/%s/interfaces/ports/%s/actions on the Official API.
	ExecutePortAction(ctx context.Context, siteId string, deviceId string, portIdx string, body PortActionRequest) error
	// GetAdoptedDetails maps to GET /v1/sites/%s/devices/%s on the Official API.
	GetAdoptedDetails(ctx context.Context, siteId string, deviceId string) (*AdoptedDeviceDetails, error)
	// GetAdoptedLatestStatistics maps to GET /v1/sites/%s/devices/%s/statistics/latest on the Official API.
	GetAdoptedLatestStatistics(ctx context.Context, siteId string, deviceId string) (*LatestStatisticsForADevice, error)
	// GetAdoptedOverviewPage maps to GET /v1/sites/%s/devices on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
	GetAdoptedOverviewPage(ctx context.Context, siteId string) ([]AdoptedDeviceOverview, error)
	// GetPendingPage maps to GET /v1/pending-devices on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
	GetPendingPage(ctx context.Context) ([]DevicePendingAdoption, error)
	// Remove maps to DELETE /v1/sites/%s/devices/%s on the Official API.
	Remove(ctx context.Context, siteId string, deviceId string) error
}

// devicesClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type devicesClient struct{ *apiClient }

var _ DevicesClient = devicesClient{}

// Devices returns the Devices resource group.
func (c *apiClient) Devices() DevicesClient {
	return devicesClient{c}
}

// Adopt maps to POST /v1/sites/%s/devices on the Official API.
func (c devicesClient) Adopt(ctx context.Context, siteId string, body DeviceAdoptionRequest) (*AdoptedDeviceDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out AdoptedDeviceDetails
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Adopt: %w", err)
	}
	return &out, nil
}

// ExecuteAdoptedAction maps to POST /v1/sites/%s/devices/%s/actions on the Official API.
func (c devicesClient) ExecuteAdoptedAction(ctx context.Context, siteId string, deviceId string, body DeviceActionRequest) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/actions", url.PathEscape(siteId), url.PathEscape(deviceId))), body, nil); err != nil {
		return fmt.Errorf("failed ExecuteAdoptedAction: %w", err)
	}
	return nil
}

// ExecutePortAction maps to POST /v1/sites/%s/devices/%s/interfaces/ports/%s/actions on the Official API.
func (c devicesClient) ExecutePortAction(ctx context.Context, siteId string, deviceId string, portIdx string, body PortActionRequest) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/interfaces/ports/%s/actions", url.PathEscape(siteId), url.PathEscape(deviceId), url.PathEscape(portIdx))), body, nil); err != nil {
		return fmt.Errorf("failed ExecutePortAction: %w", err)
	}
	return nil
}

// GetAdoptedDetails maps to GET /v1/sites/%s/devices/%s on the Official API.
func (c devicesClient) GetAdoptedDetails(ctx context.Context, siteId string, deviceId string) (*AdoptedDeviceDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out AdoptedDeviceDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s", url.PathEscape(siteId), url.PathEscape(deviceId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetAdoptedDetails: %w", err)
	}
	return &out, nil
}

// GetAdoptedLatestStatistics maps to GET /v1/sites/%s/devices/%s/statistics/latest on the Official API.
func (c devicesClient) GetAdoptedLatestStatistics(ctx context.Context, siteId string, deviceId string) (*LatestStatisticsForADevice, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out LatestStatisticsForADevice
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/statistics/latest", url.PathEscape(siteId), url.PathEscape(deviceId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetAdoptedLatestStatistics: %w", err)
	}
	return &out, nil
}

// GetAdoptedOverviewPage maps to GET /v1/sites/%s/devices on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c devicesClient) GetAdoptedOverviewPage(ctx context.Context, siteId string) ([]AdoptedDeviceOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []AdoptedDeviceOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/devices", url.PathEscape(siteId))), &out); err != nil {
		return nil, fmt.Errorf("failed GetAdoptedOverviewPage: %w", err)
	}
	return out, nil
}

// GetPendingPage maps to GET /v1/pending-devices on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c devicesClient) GetPendingPage(ctx context.Context) ([]DevicePendingAdoption, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []DevicePendingAdoption
	if err := listAll(ctx, c.doer, c.path("/pending-devices"), &out); err != nil {
		return nil, fmt.Errorf("failed GetPendingPage: %w", err)
	}
	return out, nil
}

// Remove maps to DELETE /v1/sites/%s/devices/%s on the Official API.
func (c devicesClient) Remove(ctx context.Context, siteId string, deviceId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s", url.PathEscape(siteId), url.PathEscape(deviceId))), nil, nil); err != nil {
		return fmt.Errorf("failed Remove: %w", err)
	}
	return nil
}

// DevicesClientMock is a func-field test double implementing DevicesClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type DevicesClientMock struct {
	AdoptFunc                      func(context.Context, string, DeviceAdoptionRequest) (*AdoptedDeviceDetails, error)
	ExecuteAdoptedActionFunc       func(context.Context, string, string, DeviceActionRequest) error
	ExecutePortActionFunc          func(context.Context, string, string, string, PortActionRequest) error
	GetAdoptedDetailsFunc          func(context.Context, string, string) (*AdoptedDeviceDetails, error)
	GetAdoptedLatestStatisticsFunc func(context.Context, string, string) (*LatestStatisticsForADevice, error)
	GetAdoptedOverviewPageFunc     func(context.Context, string) ([]AdoptedDeviceOverview, error)
	GetPendingPageFunc             func(context.Context) ([]DevicePendingAdoption, error)
	RemoveFunc                     func(context.Context, string, string) error
}

var _ DevicesClient = (*DevicesClientMock)(nil)

func (m *DevicesClientMock) Adopt(ctx context.Context, siteId string, body DeviceAdoptionRequest) (*AdoptedDeviceDetails, error) {
	return m.AdoptFunc(ctx, siteId, body)
}

func (m *DevicesClientMock) ExecuteAdoptedAction(ctx context.Context, siteId string, deviceId string, body DeviceActionRequest) error {
	return m.ExecuteAdoptedActionFunc(ctx, siteId, deviceId, body)
}

func (m *DevicesClientMock) ExecutePortAction(ctx context.Context, siteId string, deviceId string, portIdx string, body PortActionRequest) error {
	return m.ExecutePortActionFunc(ctx, siteId, deviceId, portIdx, body)
}

func (m *DevicesClientMock) GetAdoptedDetails(ctx context.Context, siteId string, deviceId string) (*AdoptedDeviceDetails, error) {
	return m.GetAdoptedDetailsFunc(ctx, siteId, deviceId)
}

func (m *DevicesClientMock) GetAdoptedLatestStatistics(ctx context.Context, siteId string, deviceId string) (*LatestStatisticsForADevice, error) {
	return m.GetAdoptedLatestStatisticsFunc(ctx, siteId, deviceId)
}

func (m *DevicesClientMock) GetAdoptedOverviewPage(ctx context.Context, siteId string) ([]AdoptedDeviceOverview, error) {
	return m.GetAdoptedOverviewPageFunc(ctx, siteId)
}

func (m *DevicesClientMock) GetPendingPage(ctx context.Context) ([]DevicePendingAdoption, error) {
	return m.GetPendingPageFunc(ctx)
}

func (m *DevicesClientMock) Remove(ctx context.Context, siteId string, deviceId string) error {
	return m.RemoveFunc(ctx, siteId, deviceId)
}
