// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// DNSPolicyClient is the DNSPolicy resource group of the Official UniFi OpenAPI surface.
type DNSPolicyClient interface {
	// Create maps to POST /v1/sites/%s/dns/policies on the Official API.
	Create(ctx context.Context, siteId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error)
	// Delete maps to DELETE /v1/sites/%s/dns/policies/%s on the Official API.
	Delete(ctx context.Context, siteId string, dnsPolicyId string) error
	// Get maps to GET /v1/sites/%s/dns/policies/%s on the Official API.
	Get(ctx context.Context, siteId string, dnsPolicyId string) (*DNSPolicy, error)
	// GetPage maps to GET /v1/sites/%s/dns/policies on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
	GetPage(ctx context.Context, siteId string) ([]DNSPolicy, error)
	// Update maps to PUT /v1/sites/%s/dns/policies/%s on the Official API.
	Update(ctx context.Context, siteId string, dnsPolicyId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error)
}

// dNSPolicyClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type dNSPolicyClient struct{ *apiClient }

var _ DNSPolicyClient = dNSPolicyClient{}

// DNSPolicy returns the DNSPolicy resource group.
func (c *apiClient) DNSPolicy() DNSPolicyClient {
	return dNSPolicyClient{c}
}

// Create maps to POST /v1/sites/%s/dns/policies on the Official API.
func (c dNSPolicyClient) Create(ctx context.Context, siteId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out DNSPolicy
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Create: %w", err)
	}
	return &out, nil
}

// Delete maps to DELETE /v1/sites/%s/dns/policies/%s on the Official API.
func (c dNSPolicyClient) Delete(ctx context.Context, siteId string, dnsPolicyId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies/%s", url.PathEscape(siteId), url.PathEscape(dnsPolicyId))), nil, nil); err != nil {
		return fmt.Errorf("failed Delete: %w", err)
	}
	return nil
}

// Get maps to GET /v1/sites/%s/dns/policies/%s on the Official API.
func (c dNSPolicyClient) Get(ctx context.Context, siteId string, dnsPolicyId string) (*DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out DNSPolicy
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies/%s", url.PathEscape(siteId), url.PathEscape(dnsPolicyId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed Get: %w", err)
	}
	return &out, nil
}

// GetPage maps to GET /v1/sites/%s/dns/policies on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c dNSPolicyClient) GetPage(ctx context.Context, siteId string) ([]DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []DNSPolicy
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/dns/policies", url.PathEscape(siteId))), &out); err != nil {
		return nil, fmt.Errorf("failed GetPage: %w", err)
	}
	return out, nil
}

// Update maps to PUT /v1/sites/%s/dns/policies/%s on the Official API.
func (c dNSPolicyClient) Update(ctx context.Context, siteId string, dnsPolicyId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out DNSPolicy
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies/%s", url.PathEscape(siteId), url.PathEscape(dnsPolicyId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Update: %w", err)
	}
	return &out, nil
}

// DNSPolicyClientMock is a func-field test double implementing DNSPolicyClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type DNSPolicyClientMock struct {
	CreateFunc  func(context.Context, string, DNSPolicyCreateOrUpdate) (*DNSPolicy, error)
	DeleteFunc  func(context.Context, string, string) error
	GetFunc     func(context.Context, string, string) (*DNSPolicy, error)
	GetPageFunc func(context.Context, string) ([]DNSPolicy, error)
	UpdateFunc  func(context.Context, string, string, DNSPolicyCreateOrUpdate) (*DNSPolicy, error)
}

var _ DNSPolicyClient = (*DNSPolicyClientMock)(nil)

func (m *DNSPolicyClientMock) Create(ctx context.Context, siteId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	return m.CreateFunc(ctx, siteId, body)
}

func (m *DNSPolicyClientMock) Delete(ctx context.Context, siteId string, dnsPolicyId string) error {
	return m.DeleteFunc(ctx, siteId, dnsPolicyId)
}

func (m *DNSPolicyClientMock) Get(ctx context.Context, siteId string, dnsPolicyId string) (*DNSPolicy, error) {
	return m.GetFunc(ctx, siteId, dnsPolicyId)
}

func (m *DNSPolicyClientMock) GetPage(ctx context.Context, siteId string) ([]DNSPolicy, error) {
	return m.GetPageFunc(ctx, siteId)
}

func (m *DNSPolicyClientMock) Update(ctx context.Context, siteId string, dnsPolicyId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	return m.UpdateFunc(ctx, siteId, dnsPolicyId, body)
}
