// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// DNSPoliciesClient is the DNSPolicies resource group of the Official UniFi OpenAPI surface.
type DNSPoliciesClient interface {
	// Create maps to POST /v1/sites/%s/dns/policies on the Official API.
	Create(ctx context.Context, siteId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error)
	// Delete maps to DELETE /v1/sites/%s/dns/policies/%s on the Official API.
	Delete(ctx context.Context, siteId string, dnsPolicyId string) error
	// Get maps to GET /v1/sites/%s/dns/policies/%s on the Official API.
	Get(ctx context.Context, siteId string, dnsPolicyId string) (*DNSPolicy, error)
	// List maps to GET /v1/sites/%s/dns/policies on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
	List(ctx context.Context, siteId string, opts ...ListOption) ([]DNSPolicy, error)
	// Update maps to PUT /v1/sites/%s/dns/policies/%s on the Official API.
	Update(ctx context.Context, siteId string, dnsPolicyId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error)
}

// dNSPoliciesClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type dNSPoliciesClient struct{ *apiClient }

var _ DNSPoliciesClient = dNSPoliciesClient{}

// DNSPolicies returns the DNSPolicies resource group.
func (c *apiClient) DNSPolicies() DNSPoliciesClient {
	return dNSPoliciesClient{c}
}

// Create maps to POST /v1/sites/%s/dns/policies on the Official API.
func (c dNSPoliciesClient) Create(ctx context.Context, siteId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out DNSPolicy
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Create: %w", err)
	}
	return &out, nil
}

// Delete maps to DELETE /v1/sites/%s/dns/policies/%s on the Official API.
func (c dNSPoliciesClient) Delete(ctx context.Context, siteId string, dnsPolicyId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies/%s", url.PathEscape(siteId), url.PathEscape(dnsPolicyId))), nil, nil); err != nil {
		return fmt.Errorf("failed Delete: %w", err)
	}
	return nil
}

// Get maps to GET /v1/sites/%s/dns/policies/%s on the Official API.
func (c dNSPoliciesClient) Get(ctx context.Context, siteId string, dnsPolicyId string) (*DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out DNSPolicy
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies/%s", url.PathEscape(siteId), url.PathEscape(dnsPolicyId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed Get: %w", err)
	}
	return &out, nil
}

// List maps to GET /v1/sites/%s/dns/policies on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
func (c dNSPoliciesClient) List(ctx context.Context, siteId string, opts ...ListOption) ([]DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []DNSPolicy
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/dns/policies", url.PathEscape(siteId))), &out, opts...); err != nil {
		return nil, fmt.Errorf("failed List: %w", err)
	}
	return out, nil
}

// Update maps to PUT /v1/sites/%s/dns/policies/%s on the Official API.
func (c dNSPoliciesClient) Update(ctx context.Context, siteId string, dnsPolicyId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out DNSPolicy
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies/%s", url.PathEscape(siteId), url.PathEscape(dnsPolicyId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Update: %w", err)
	}
	return &out, nil
}

// DNSPoliciesClientMock is a func-field test double implementing DNSPoliciesClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type DNSPoliciesClientMock struct {
	CreateFunc func(context.Context, string, DNSPolicyCreateOrUpdate) (*DNSPolicy, error)
	DeleteFunc func(context.Context, string, string) error
	GetFunc    func(context.Context, string, string) (*DNSPolicy, error)
	ListFunc   func(context.Context, string, ...ListOption) ([]DNSPolicy, error)
	UpdateFunc func(context.Context, string, string, DNSPolicyCreateOrUpdate) (*DNSPolicy, error)
}

var _ DNSPoliciesClient = (*DNSPoliciesClientMock)(nil)

func (m *DNSPoliciesClientMock) Create(ctx context.Context, siteId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	return m.CreateFunc(ctx, siteId, body)
}

func (m *DNSPoliciesClientMock) Delete(ctx context.Context, siteId string, dnsPolicyId string) error {
	return m.DeleteFunc(ctx, siteId, dnsPolicyId)
}

func (m *DNSPoliciesClientMock) Get(ctx context.Context, siteId string, dnsPolicyId string) (*DNSPolicy, error) {
	return m.GetFunc(ctx, siteId, dnsPolicyId)
}

func (m *DNSPoliciesClientMock) List(ctx context.Context, siteId string, opts ...ListOption) ([]DNSPolicy, error) {
	return m.ListFunc(ctx, siteId, opts...)
}

func (m *DNSPoliciesClientMock) Update(ctx context.Context, siteId string, dnsPolicyId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	return m.UpdateFunc(ctx, siteId, dnsPolicyId, body)
}
