// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"iter"
	"net/url"

	"github.com/google/uuid"
)

// FirewallClient is the Firewall resource group of the Official UniFi OpenAPI surface.
type FirewallClient interface {
	// CreatePolicy maps to POST /v1/sites/%s/firewall/policies on the Official API.
	CreatePolicy(ctx context.Context, siteId uuid.UUID, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error)
	// CreateZone maps to POST /v1/sites/%s/firewall/zones on the Official API.
	CreateZone(ctx context.Context, siteId uuid.UUID, body FirewallZoneCreateOrUpdate) (*FirewallZone, error)
	// DeletePolicy maps to DELETE /v1/sites/%s/firewall/policies/%s on the Official API.
	DeletePolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID) error
	// DeleteZone maps to DELETE /v1/sites/%s/firewall/zones/%s on the Official API.
	DeleteZone(ctx context.Context, siteId uuid.UUID, firewallZoneId uuid.UUID) error
	// GetPolicy maps to GET /v1/sites/%s/firewall/policies/%s on the Official API.
	GetPolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID) (*FirewallPolicy, error)
	// GetPolicyOrdering maps to GET /v1/sites/%s/firewall/policies/ordering on the Official API.
	GetPolicyOrdering(ctx context.Context, siteId uuid.UUID, sourceFirewallZoneId string, destinationFirewallZoneId string) (*FirewallPolicyOrdering, error)
	// GetZone maps to GET /v1/sites/%s/firewall/zones/%s on the Official API.
	GetZone(ctx context.Context, siteId uuid.UUID, firewallZoneId uuid.UUID) (*FirewallZone, error)
	// ListPoliciesAll lazily drains every item from GET /v1/sites/%s/firewall/policies, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListPoliciesAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[FirewallPolicy, error]
	// ListPoliciesPage returns one page from GET /v1/sites/%s/firewall/policies; nil opts fetches the first page at the default size.
	ListPoliciesPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[FirewallPolicy], error)
	// ListZonesAll lazily drains every item from GET /v1/sites/%s/firewall/zones, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListZonesAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[FirewallZone, error]
	// ListZonesPage returns one page from GET /v1/sites/%s/firewall/zones; nil opts fetches the first page at the default size.
	ListZonesPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[FirewallZone], error)
	// PatchPolicy maps to PATCH /v1/sites/%s/firewall/policies/%s on the Official API.
	PatchPolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID, body PatchFirewallPolicy) (*FirewallPolicy, error)
	// UpdatePolicy maps to PUT /v1/sites/%s/firewall/policies/%s on the Official API.
	UpdatePolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error)
	// UpdatePolicyOrdering maps to PUT /v1/sites/%s/firewall/policies/ordering on the Official API.
	UpdatePolicyOrdering(ctx context.Context, siteId uuid.UUID, sourceFirewallZoneId string, destinationFirewallZoneId string, body FirewallPolicyOrdering) (*FirewallPolicyOrdering, error)
	// UpdateZone maps to PUT /v1/sites/%s/firewall/zones/%s on the Official API.
	UpdateZone(ctx context.Context, siteId uuid.UUID, firewallZoneId uuid.UUID, body FirewallZoneCreateOrUpdate) (*FirewallZone, error)
}

// firewallClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type firewallClient struct{ *apiClient }

var _ FirewallClient = firewallClient{}

// Firewall returns the Firewall resource group.
func (c *apiClient) Firewall() FirewallClient {
	return firewallClient{c}
}

// CreatePolicy maps to POST /v1/sites/%s/firewall/policies on the Official API.
func (c firewallClient) CreatePolicy(ctx context.Context, siteId uuid.UUID, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies", siteId.String())), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreatePolicy: %w", err)
	}
	return &out, nil
}

// CreateZone maps to POST /v1/sites/%s/firewall/zones on the Official API.
func (c firewallClient) CreateZone(ctx context.Context, siteId uuid.UUID, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallZone
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones", siteId.String())), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateZone: %w", err)
	}
	return &out, nil
}

// DeletePolicy maps to DELETE /v1/sites/%s/firewall/policies/%s on the Official API.
func (c firewallClient) DeletePolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", siteId.String(), firewallPolicyId.String())), nil, nil); err != nil {
		return fmt.Errorf("failed DeletePolicy: %w", err)
	}
	return nil
}

// DeleteZone maps to DELETE /v1/sites/%s/firewall/zones/%s on the Official API.
func (c firewallClient) DeleteZone(ctx context.Context, siteId uuid.UUID, firewallZoneId uuid.UUID) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones/%s", siteId.String(), firewallZoneId.String())), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteZone: %w", err)
	}
	return nil
}

// GetPolicy maps to GET /v1/sites/%s/firewall/policies/%s on the Official API.
func (c firewallClient) GetPolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", siteId.String(), firewallPolicyId.String())), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetPolicy: %w", err)
	}
	return &out, nil
}

// GetPolicyOrdering maps to GET /v1/sites/%s/firewall/policies/ordering on the Official API.
func (c firewallClient) GetPolicyOrdering(ctx context.Context, siteId uuid.UUID, sourceFirewallZoneId string, destinationFirewallZoneId string) (*FirewallPolicyOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicyOrdering
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/ordering?sourceFirewallZoneId=%s&destinationFirewallZoneId=%s", siteId.String(), url.QueryEscape(sourceFirewallZoneId), url.QueryEscape(destinationFirewallZoneId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetPolicyOrdering: %w", err)
	}
	return &out, nil
}

// GetZone maps to GET /v1/sites/%s/firewall/zones/%s on the Official API.
func (c firewallClient) GetZone(ctx context.Context, siteId uuid.UUID, firewallZoneId uuid.UUID) (*FirewallZone, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallZone
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones/%s", siteId.String(), firewallZoneId.String())), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetZone: %w", err)
	}
	return &out, nil
}

// ListPoliciesAll lazily drains every item from GET /v1/sites/%s/firewall/policies, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c firewallClient) ListPoliciesAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[FirewallPolicy, error] {
	return listSeq[FirewallPolicy](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/firewall/policies", siteId.String())), filter)
}

// ListPoliciesPage returns one page from GET /v1/sites/%s/firewall/policies; nil opts fetches the first page at the default size.
func (c firewallClient) ListPoliciesPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[FirewallPolicy], error) {
	if err := c.check(ctx); err != nil {
		return Page[FirewallPolicy]{}, err
	}
	p, err := listPage[FirewallPolicy](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/firewall/policies", siteId.String())), opts)
	if err != nil {
		return Page[FirewallPolicy]{}, fmt.Errorf("failed ListPoliciesPage: %w", err)
	}
	return p, nil
}

// ListZonesAll lazily drains every item from GET /v1/sites/%s/firewall/zones, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c firewallClient) ListZonesAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[FirewallZone, error] {
	return listSeq[FirewallZone](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/firewall/zones", siteId.String())), filter)
}

// ListZonesPage returns one page from GET /v1/sites/%s/firewall/zones; nil opts fetches the first page at the default size.
func (c firewallClient) ListZonesPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[FirewallZone], error) {
	if err := c.check(ctx); err != nil {
		return Page[FirewallZone]{}, err
	}
	p, err := listPage[FirewallZone](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/firewall/zones", siteId.String())), opts)
	if err != nil {
		return Page[FirewallZone]{}, fmt.Errorf("failed ListZonesPage: %w", err)
	}
	return p, nil
}

// PatchPolicy maps to PATCH /v1/sites/%s/firewall/policies/%s on the Official API.
func (c firewallClient) PatchPolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID, body PatchFirewallPolicy) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Patch(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", siteId.String(), firewallPolicyId.String())), body, &out); err != nil {
		return nil, fmt.Errorf("failed PatchPolicy: %w", err)
	}
	return &out, nil
}

// UpdatePolicy maps to PUT /v1/sites/%s/firewall/policies/%s on the Official API.
func (c firewallClient) UpdatePolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", siteId.String(), firewallPolicyId.String())), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdatePolicy: %w", err)
	}
	return &out, nil
}

// UpdatePolicyOrdering maps to PUT /v1/sites/%s/firewall/policies/ordering on the Official API.
func (c firewallClient) UpdatePolicyOrdering(ctx context.Context, siteId uuid.UUID, sourceFirewallZoneId string, destinationFirewallZoneId string, body FirewallPolicyOrdering) (*FirewallPolicyOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicyOrdering
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/ordering?sourceFirewallZoneId=%s&destinationFirewallZoneId=%s", siteId.String(), url.QueryEscape(sourceFirewallZoneId), url.QueryEscape(destinationFirewallZoneId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdatePolicyOrdering: %w", err)
	}
	return &out, nil
}

// UpdateZone maps to PUT /v1/sites/%s/firewall/zones/%s on the Official API.
func (c firewallClient) UpdateZone(ctx context.Context, siteId uuid.UUID, firewallZoneId uuid.UUID, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallZone
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones/%s", siteId.String(), firewallZoneId.String())), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateZone: %w", err)
	}
	return &out, nil
}

// FirewallClientMock is a func-field test double implementing FirewallClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type FirewallClientMock struct {
	CreatePolicyFunc         func(context.Context, uuid.UUID, FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error)
	CreateZoneFunc           func(context.Context, uuid.UUID, FirewallZoneCreateOrUpdate) (*FirewallZone, error)
	DeletePolicyFunc         func(context.Context, uuid.UUID, uuid.UUID) error
	DeleteZoneFunc           func(context.Context, uuid.UUID, uuid.UUID) error
	GetPolicyFunc            func(context.Context, uuid.UUID, uuid.UUID) (*FirewallPolicy, error)
	GetPolicyOrderingFunc    func(context.Context, uuid.UUID, string, string) (*FirewallPolicyOrdering, error)
	GetZoneFunc              func(context.Context, uuid.UUID, uuid.UUID) (*FirewallZone, error)
	ListPoliciesAllFunc      func(context.Context, uuid.UUID, string) iter.Seq2[FirewallPolicy, error]
	ListPoliciesPageFunc     func(context.Context, uuid.UUID, *ListOptions) (Page[FirewallPolicy], error)
	ListZonesAllFunc         func(context.Context, uuid.UUID, string) iter.Seq2[FirewallZone, error]
	ListZonesPageFunc        func(context.Context, uuid.UUID, *ListOptions) (Page[FirewallZone], error)
	PatchPolicyFunc          func(context.Context, uuid.UUID, uuid.UUID, PatchFirewallPolicy) (*FirewallPolicy, error)
	UpdatePolicyFunc         func(context.Context, uuid.UUID, uuid.UUID, FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error)
	UpdatePolicyOrderingFunc func(context.Context, uuid.UUID, string, string, FirewallPolicyOrdering) (*FirewallPolicyOrdering, error)
	UpdateZoneFunc           func(context.Context, uuid.UUID, uuid.UUID, FirewallZoneCreateOrUpdate) (*FirewallZone, error)
}

var _ FirewallClient = (*FirewallClientMock)(nil)

func (m *FirewallClientMock) CreatePolicy(ctx context.Context, siteId uuid.UUID, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	return m.CreatePolicyFunc(ctx, siteId, body)
}

func (m *FirewallClientMock) CreateZone(ctx context.Context, siteId uuid.UUID, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	return m.CreateZoneFunc(ctx, siteId, body)
}

func (m *FirewallClientMock) DeletePolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID) error {
	return m.DeletePolicyFunc(ctx, siteId, firewallPolicyId)
}

func (m *FirewallClientMock) DeleteZone(ctx context.Context, siteId uuid.UUID, firewallZoneId uuid.UUID) error {
	return m.DeleteZoneFunc(ctx, siteId, firewallZoneId)
}

func (m *FirewallClientMock) GetPolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID) (*FirewallPolicy, error) {
	return m.GetPolicyFunc(ctx, siteId, firewallPolicyId)
}

func (m *FirewallClientMock) GetPolicyOrdering(ctx context.Context, siteId uuid.UUID, sourceFirewallZoneId string, destinationFirewallZoneId string) (*FirewallPolicyOrdering, error) {
	return m.GetPolicyOrderingFunc(ctx, siteId, sourceFirewallZoneId, destinationFirewallZoneId)
}

func (m *FirewallClientMock) GetZone(ctx context.Context, siteId uuid.UUID, firewallZoneId uuid.UUID) (*FirewallZone, error) {
	return m.GetZoneFunc(ctx, siteId, firewallZoneId)
}

func (m *FirewallClientMock) ListPoliciesAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[FirewallPolicy, error] {
	return m.ListPoliciesAllFunc(ctx, siteId, filter)
}

func (m *FirewallClientMock) ListPoliciesPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[FirewallPolicy], error) {
	return m.ListPoliciesPageFunc(ctx, siteId, opts)
}

func (m *FirewallClientMock) ListZonesAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[FirewallZone, error] {
	return m.ListZonesAllFunc(ctx, siteId, filter)
}

func (m *FirewallClientMock) ListZonesPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[FirewallZone], error) {
	return m.ListZonesPageFunc(ctx, siteId, opts)
}

func (m *FirewallClientMock) PatchPolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID, body PatchFirewallPolicy) (*FirewallPolicy, error) {
	return m.PatchPolicyFunc(ctx, siteId, firewallPolicyId, body)
}

func (m *FirewallClientMock) UpdatePolicy(ctx context.Context, siteId uuid.UUID, firewallPolicyId uuid.UUID, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	return m.UpdatePolicyFunc(ctx, siteId, firewallPolicyId, body)
}

func (m *FirewallClientMock) UpdatePolicyOrdering(ctx context.Context, siteId uuid.UUID, sourceFirewallZoneId string, destinationFirewallZoneId string, body FirewallPolicyOrdering) (*FirewallPolicyOrdering, error) {
	return m.UpdatePolicyOrderingFunc(ctx, siteId, sourceFirewallZoneId, destinationFirewallZoneId, body)
}

func (m *FirewallClientMock) UpdateZone(ctx context.Context, siteId uuid.UUID, firewallZoneId uuid.UUID, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	return m.UpdateZoneFunc(ctx, siteId, firewallZoneId, body)
}
