// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// FirewallClient is the Firewall resource group of the Official UniFi OpenAPI surface.
type FirewallClient interface {
	// CreatePolicy maps to POST /v1/sites/%s/firewall/policies on the Official API.
	CreatePolicy(ctx context.Context, siteId string, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error)
	// CreateZone maps to POST /v1/sites/%s/firewall/zones on the Official API.
	CreateZone(ctx context.Context, siteId string, body FirewallZoneCreateOrUpdate) (*FirewallZone, error)
	// DeletePolicy maps to DELETE /v1/sites/%s/firewall/policies/%s on the Official API.
	DeletePolicy(ctx context.Context, siteId string, firewallPolicyId string) error
	// DeleteZone maps to DELETE /v1/sites/%s/firewall/zones/%s on the Official API.
	DeleteZone(ctx context.Context, siteId string, firewallZoneId string) error
	// GetPolicy maps to GET /v1/sites/%s/firewall/policies/%s on the Official API.
	GetPolicy(ctx context.Context, siteId string, firewallPolicyId string) (*FirewallPolicy, error)
	// GetPolicyOrdering maps to GET /v1/sites/%s/firewall/policies/ordering on the Official API.
	GetPolicyOrdering(ctx context.Context, siteId string, sourceFirewallZoneId string, destinationFirewallZoneId string) (*FirewallPolicyOrdering, error)
	// GetZone maps to GET /v1/sites/%s/firewall/zones/%s on the Official API.
	GetZone(ctx context.Context, siteId string, firewallZoneId string) (*FirewallZone, error)
	// ListPolicies maps to GET /v1/sites/%s/firewall/policies on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
	ListPolicies(ctx context.Context, siteId string, opts ...ListOption) ([]FirewallPolicy, error)
	// ListZones maps to GET /v1/sites/%s/firewall/zones on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
	ListZones(ctx context.Context, siteId string, opts ...ListOption) ([]FirewallZone, error)
	// PatchPolicy maps to PATCH /v1/sites/%s/firewall/policies/%s on the Official API.
	PatchPolicy(ctx context.Context, siteId string, firewallPolicyId string, body PatchFirewallPolicy) (*FirewallPolicy, error)
	// UpdatePolicy maps to PUT /v1/sites/%s/firewall/policies/%s on the Official API.
	UpdatePolicy(ctx context.Context, siteId string, firewallPolicyId string, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error)
	// UpdatePolicyOrdering maps to PUT /v1/sites/%s/firewall/policies/ordering on the Official API.
	UpdatePolicyOrdering(ctx context.Context, siteId string, sourceFirewallZoneId string, destinationFirewallZoneId string, body FirewallPolicyOrdering) (*FirewallPolicyOrdering, error)
	// UpdateZone maps to PUT /v1/sites/%s/firewall/zones/%s on the Official API.
	UpdateZone(ctx context.Context, siteId string, firewallZoneId string, body FirewallZoneCreateOrUpdate) (*FirewallZone, error)
}

// firewallClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type firewallClient struct{ *apiClient }

var _ FirewallClient = firewallClient{}

// Firewall returns the Firewall resource group.
func (c *apiClient) Firewall() FirewallClient {
	return firewallClient{c}
}

// CreatePolicy maps to POST /v1/sites/%s/firewall/policies on the Official API.
func (c firewallClient) CreatePolicy(ctx context.Context, siteId string, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreatePolicy: %w", err)
	}
	return &out, nil
}

// CreateZone maps to POST /v1/sites/%s/firewall/zones on the Official API.
func (c firewallClient) CreateZone(ctx context.Context, siteId string, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallZone
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateZone: %w", err)
	}
	return &out, nil
}

// DeletePolicy maps to DELETE /v1/sites/%s/firewall/policies/%s on the Official API.
func (c firewallClient) DeletePolicy(ctx context.Context, siteId string, firewallPolicyId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", url.PathEscape(siteId), url.PathEscape(firewallPolicyId))), nil, nil); err != nil {
		return fmt.Errorf("failed DeletePolicy: %w", err)
	}
	return nil
}

// DeleteZone maps to DELETE /v1/sites/%s/firewall/zones/%s on the Official API.
func (c firewallClient) DeleteZone(ctx context.Context, siteId string, firewallZoneId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones/%s", url.PathEscape(siteId), url.PathEscape(firewallZoneId))), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteZone: %w", err)
	}
	return nil
}

// GetPolicy maps to GET /v1/sites/%s/firewall/policies/%s on the Official API.
func (c firewallClient) GetPolicy(ctx context.Context, siteId string, firewallPolicyId string) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", url.PathEscape(siteId), url.PathEscape(firewallPolicyId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetPolicy: %w", err)
	}
	return &out, nil
}

// GetPolicyOrdering maps to GET /v1/sites/%s/firewall/policies/ordering on the Official API.
func (c firewallClient) GetPolicyOrdering(ctx context.Context, siteId string, sourceFirewallZoneId string, destinationFirewallZoneId string) (*FirewallPolicyOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicyOrdering
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/ordering?sourceFirewallZoneId=%s&destinationFirewallZoneId=%s", url.PathEscape(siteId), url.QueryEscape(sourceFirewallZoneId), url.QueryEscape(destinationFirewallZoneId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetPolicyOrdering: %w", err)
	}
	return &out, nil
}

// GetZone maps to GET /v1/sites/%s/firewall/zones/%s on the Official API.
func (c firewallClient) GetZone(ctx context.Context, siteId string, firewallZoneId string) (*FirewallZone, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallZone
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones/%s", url.PathEscape(siteId), url.PathEscape(firewallZoneId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetZone: %w", err)
	}
	return &out, nil
}

// ListPolicies maps to GET /v1/sites/%s/firewall/policies on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
func (c firewallClient) ListPolicies(ctx context.Context, siteId string, opts ...ListOption) ([]FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []FirewallPolicy
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/firewall/policies", url.PathEscape(siteId))), &out, opts...); err != nil {
		return nil, fmt.Errorf("failed ListPolicies: %w", err)
	}
	return out, nil
}

// ListZones maps to GET /v1/sites/%s/firewall/zones on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
func (c firewallClient) ListZones(ctx context.Context, siteId string, opts ...ListOption) ([]FirewallZone, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []FirewallZone
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/firewall/zones", url.PathEscape(siteId))), &out, opts...); err != nil {
		return nil, fmt.Errorf("failed ListZones: %w", err)
	}
	return out, nil
}

// PatchPolicy maps to PATCH /v1/sites/%s/firewall/policies/%s on the Official API.
func (c firewallClient) PatchPolicy(ctx context.Context, siteId string, firewallPolicyId string, body PatchFirewallPolicy) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Patch(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", url.PathEscape(siteId), url.PathEscape(firewallPolicyId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed PatchPolicy: %w", err)
	}
	return &out, nil
}

// UpdatePolicy maps to PUT /v1/sites/%s/firewall/policies/%s on the Official API.
func (c firewallClient) UpdatePolicy(ctx context.Context, siteId string, firewallPolicyId string, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", url.PathEscape(siteId), url.PathEscape(firewallPolicyId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdatePolicy: %w", err)
	}
	return &out, nil
}

// UpdatePolicyOrdering maps to PUT /v1/sites/%s/firewall/policies/ordering on the Official API.
func (c firewallClient) UpdatePolicyOrdering(ctx context.Context, siteId string, sourceFirewallZoneId string, destinationFirewallZoneId string, body FirewallPolicyOrdering) (*FirewallPolicyOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicyOrdering
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/ordering?sourceFirewallZoneId=%s&destinationFirewallZoneId=%s", url.PathEscape(siteId), url.QueryEscape(sourceFirewallZoneId), url.QueryEscape(destinationFirewallZoneId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdatePolicyOrdering: %w", err)
	}
	return &out, nil
}

// UpdateZone maps to PUT /v1/sites/%s/firewall/zones/%s on the Official API.
func (c firewallClient) UpdateZone(ctx context.Context, siteId string, firewallZoneId string, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallZone
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones/%s", url.PathEscape(siteId), url.PathEscape(firewallZoneId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateZone: %w", err)
	}
	return &out, nil
}

// FirewallClientMock is a func-field test double implementing FirewallClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type FirewallClientMock struct {
	CreatePolicyFunc         func(context.Context, string, FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error)
	CreateZoneFunc           func(context.Context, string, FirewallZoneCreateOrUpdate) (*FirewallZone, error)
	DeletePolicyFunc         func(context.Context, string, string) error
	DeleteZoneFunc           func(context.Context, string, string) error
	GetPolicyFunc            func(context.Context, string, string) (*FirewallPolicy, error)
	GetPolicyOrderingFunc    func(context.Context, string, string, string) (*FirewallPolicyOrdering, error)
	GetZoneFunc              func(context.Context, string, string) (*FirewallZone, error)
	ListPoliciesFunc         func(context.Context, string, ...ListOption) ([]FirewallPolicy, error)
	ListZonesFunc            func(context.Context, string, ...ListOption) ([]FirewallZone, error)
	PatchPolicyFunc          func(context.Context, string, string, PatchFirewallPolicy) (*FirewallPolicy, error)
	UpdatePolicyFunc         func(context.Context, string, string, FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error)
	UpdatePolicyOrderingFunc func(context.Context, string, string, string, FirewallPolicyOrdering) (*FirewallPolicyOrdering, error)
	UpdateZoneFunc           func(context.Context, string, string, FirewallZoneCreateOrUpdate) (*FirewallZone, error)
}

var _ FirewallClient = (*FirewallClientMock)(nil)

func (m *FirewallClientMock) CreatePolicy(ctx context.Context, siteId string, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	return m.CreatePolicyFunc(ctx, siteId, body)
}

func (m *FirewallClientMock) CreateZone(ctx context.Context, siteId string, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	return m.CreateZoneFunc(ctx, siteId, body)
}

func (m *FirewallClientMock) DeletePolicy(ctx context.Context, siteId string, firewallPolicyId string) error {
	return m.DeletePolicyFunc(ctx, siteId, firewallPolicyId)
}

func (m *FirewallClientMock) DeleteZone(ctx context.Context, siteId string, firewallZoneId string) error {
	return m.DeleteZoneFunc(ctx, siteId, firewallZoneId)
}

func (m *FirewallClientMock) GetPolicy(ctx context.Context, siteId string, firewallPolicyId string) (*FirewallPolicy, error) {
	return m.GetPolicyFunc(ctx, siteId, firewallPolicyId)
}

func (m *FirewallClientMock) GetPolicyOrdering(ctx context.Context, siteId string, sourceFirewallZoneId string, destinationFirewallZoneId string) (*FirewallPolicyOrdering, error) {
	return m.GetPolicyOrderingFunc(ctx, siteId, sourceFirewallZoneId, destinationFirewallZoneId)
}

func (m *FirewallClientMock) GetZone(ctx context.Context, siteId string, firewallZoneId string) (*FirewallZone, error) {
	return m.GetZoneFunc(ctx, siteId, firewallZoneId)
}

func (m *FirewallClientMock) ListPolicies(ctx context.Context, siteId string, opts ...ListOption) ([]FirewallPolicy, error) {
	return m.ListPoliciesFunc(ctx, siteId, opts...)
}

func (m *FirewallClientMock) ListZones(ctx context.Context, siteId string, opts ...ListOption) ([]FirewallZone, error) {
	return m.ListZonesFunc(ctx, siteId, opts...)
}

func (m *FirewallClientMock) PatchPolicy(ctx context.Context, siteId string, firewallPolicyId string, body PatchFirewallPolicy) (*FirewallPolicy, error) {
	return m.PatchPolicyFunc(ctx, siteId, firewallPolicyId, body)
}

func (m *FirewallClientMock) UpdatePolicy(ctx context.Context, siteId string, firewallPolicyId string, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	return m.UpdatePolicyFunc(ctx, siteId, firewallPolicyId, body)
}

func (m *FirewallClientMock) UpdatePolicyOrdering(ctx context.Context, siteId string, sourceFirewallZoneId string, destinationFirewallZoneId string, body FirewallPolicyOrdering) (*FirewallPolicyOrdering, error) {
	return m.UpdatePolicyOrderingFunc(ctx, siteId, sourceFirewallZoneId, destinationFirewallZoneId, body)
}

func (m *FirewallClientMock) UpdateZone(ctx context.Context, siteId string, firewallZoneId string, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	return m.UpdateZoneFunc(ctx, siteId, firewallZoneId, body)
}
