// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"errors"
	"fmt"
	"net/url"
)

// HotspotClient is the Hotspot resource group of the Official UniFi OpenAPI surface.
type HotspotClient interface {
	// CreateVouchers maps to POST /v1/sites/%s/hotspot/vouchers on the Official API.
	CreateVouchers(ctx context.Context, siteId string, body HotspotVoucherCreationRequest) (*VoucherCreationResult, error)
	// DeleteVoucher maps to DELETE /v1/sites/%s/hotspot/vouchers/%s on the Official API.
	DeleteVoucher(ctx context.Context, siteId string, voucherId string) (*VoucherDeletionResults, error)
	// DeleteVouchers maps to DELETE /v1/sites/%s/hotspot/vouchers on the Official API.
	DeleteVouchers(ctx context.Context, siteId string, filter string) (*VoucherDeletionResults, error)
	// GetVoucher maps to GET /v1/sites/%s/hotspot/vouchers/%s on the Official API.
	GetVoucher(ctx context.Context, siteId string, voucherId string) (*HotspotVoucherDetails, error)
	// ListVouchers maps to GET /v1/sites/%s/hotspot/vouchers on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
	ListVouchers(ctx context.Context, siteId string, opts ...ListOption) ([]HotspotVoucherDetails, error)
}

// hotspotClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type hotspotClient struct{ *apiClient }

var _ HotspotClient = hotspotClient{}

// Hotspot returns the Hotspot resource group.
func (c *apiClient) Hotspot() HotspotClient {
	return hotspotClient{c}
}

// CreateVouchers maps to POST /v1/sites/%s/hotspot/vouchers on the Official API.
func (c hotspotClient) CreateVouchers(ctx context.Context, siteId string, body HotspotVoucherCreationRequest) (*VoucherCreationResult, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out VoucherCreationResult
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/hotspot/vouchers", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateVouchers: %w", err)
	}
	return &out, nil
}

// DeleteVoucher maps to DELETE /v1/sites/%s/hotspot/vouchers/%s on the Official API.
func (c hotspotClient) DeleteVoucher(ctx context.Context, siteId string, voucherId string) (*VoucherDeletionResults, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out VoucherDeletionResults
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/hotspot/vouchers/%s", url.PathEscape(siteId), url.PathEscape(voucherId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed DeleteVoucher: %w", err)
	}
	return &out, nil
}

// DeleteVouchers maps to DELETE /v1/sites/%s/hotspot/vouchers on the Official API.
func (c hotspotClient) DeleteVouchers(ctx context.Context, siteId string, filter string) (*VoucherDeletionResults, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	if filter == "" {
		return nil, errors.New("filter must not be empty")
	}
	var out VoucherDeletionResults
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/hotspot/vouchers?filter=%s", url.PathEscape(siteId), url.QueryEscape(filter))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed DeleteVouchers: %w", err)
	}
	return &out, nil
}

// GetVoucher maps to GET /v1/sites/%s/hotspot/vouchers/%s on the Official API.
func (c hotspotClient) GetVoucher(ctx context.Context, siteId string, voucherId string) (*HotspotVoucherDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out HotspotVoucherDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/hotspot/vouchers/%s", url.PathEscape(siteId), url.PathEscape(voucherId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetVoucher: %w", err)
	}
	return &out, nil
}

// ListVouchers maps to GET /v1/sites/%s/hotspot/vouchers on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
func (c hotspotClient) ListVouchers(ctx context.Context, siteId string, opts ...ListOption) ([]HotspotVoucherDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []HotspotVoucherDetails
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/hotspot/vouchers", url.PathEscape(siteId))), &out, opts...); err != nil {
		return nil, fmt.Errorf("failed ListVouchers: %w", err)
	}
	return out, nil
}

// HotspotClientMock is a func-field test double implementing HotspotClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type HotspotClientMock struct {
	CreateVouchersFunc func(context.Context, string, HotspotVoucherCreationRequest) (*VoucherCreationResult, error)
	DeleteVoucherFunc  func(context.Context, string, string) (*VoucherDeletionResults, error)
	DeleteVouchersFunc func(context.Context, string, string) (*VoucherDeletionResults, error)
	GetVoucherFunc     func(context.Context, string, string) (*HotspotVoucherDetails, error)
	ListVouchersFunc   func(context.Context, string, ...ListOption) ([]HotspotVoucherDetails, error)
}

var _ HotspotClient = (*HotspotClientMock)(nil)

func (m *HotspotClientMock) CreateVouchers(ctx context.Context, siteId string, body HotspotVoucherCreationRequest) (*VoucherCreationResult, error) {
	return m.CreateVouchersFunc(ctx, siteId, body)
}

func (m *HotspotClientMock) DeleteVoucher(ctx context.Context, siteId string, voucherId string) (*VoucherDeletionResults, error) {
	return m.DeleteVoucherFunc(ctx, siteId, voucherId)
}

func (m *HotspotClientMock) DeleteVouchers(ctx context.Context, siteId string, filter string) (*VoucherDeletionResults, error) {
	return m.DeleteVouchersFunc(ctx, siteId, filter)
}

func (m *HotspotClientMock) GetVoucher(ctx context.Context, siteId string, voucherId string) (*HotspotVoucherDetails, error) {
	return m.GetVoucherFunc(ctx, siteId, voucherId)
}

func (m *HotspotClientMock) ListVouchers(ctx context.Context, siteId string, opts ...ListOption) ([]HotspotVoucherDetails, error) {
	return m.ListVouchersFunc(ctx, siteId, opts...)
}
