// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import "context"

// InfoClient is the Info resource group of the Official UniFi OpenAPI surface.
type InfoClient interface {
	// Get returns the controller application info (GET /v1/info).
	Get(ctx context.Context) (*Info, error)
}

// infoClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type infoClient struct{ *apiClient }

var _ InfoClient = infoClient{}

// Info returns the Info resource group.
func (c *apiClient) Info() InfoClient {
	return infoClient{c}
}

// InfoClientMock is a func-field test double implementing InfoClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type InfoClientMock struct {
	GetFunc func(context.Context) (*Info, error)
}

var _ InfoClient = (*InfoClientMock)(nil)

func (m *InfoClientMock) Get(ctx context.Context) (*Info, error) {
	return m.GetFunc(ctx)
}
