// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// NetworksClient is the Networks resource group of the Official UniFi OpenAPI surface.
type NetworksClient interface {
	// Create maps to POST /v1/sites/%s/networks on the Official API.
	Create(ctx context.Context, siteId string, body NetworkCreateOrUpdate) (*NetworkDetails, error)
	// Delete maps to DELETE /v1/sites/%s/networks/%s on the Official API.
	Delete(ctx context.Context, siteId string, networkId string) error
	// Get maps to GET /v1/sites/%s/networks/%s on the Official API.
	Get(ctx context.Context, siteId string, networkId string) (*NetworkDetails, error)
	// GetReferences maps to GET /v1/sites/%s/networks/%s/references on the Official API.
	GetReferences(ctx context.Context, siteId string, networkId string) (*NetworkReferences, error)
	// List maps to GET /v1/sites/%s/networks on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
	List(ctx context.Context, siteId string, opts ...ListOption) ([]NetworkOverview, error)
	// Update maps to PUT /v1/sites/%s/networks/%s on the Official API.
	Update(ctx context.Context, siteId string, networkId string, body NetworkCreateOrUpdate) (*NetworkDetails, error)
}

// networksClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type networksClient struct{ *apiClient }

var _ NetworksClient = networksClient{}

// Networks returns the Networks resource group.
func (c *apiClient) Networks() NetworksClient {
	return networksClient{c}
}

// Create maps to POST /v1/sites/%s/networks on the Official API.
func (c networksClient) Create(ctx context.Context, siteId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkDetails
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/networks", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Create: %w", err)
	}
	return &out, nil
}

// Delete maps to DELETE /v1/sites/%s/networks/%s on the Official API.
func (c networksClient) Delete(ctx context.Context, siteId string, networkId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s", url.PathEscape(siteId), url.PathEscape(networkId))), nil, nil); err != nil {
		return fmt.Errorf("failed Delete: %w", err)
	}
	return nil
}

// Get maps to GET /v1/sites/%s/networks/%s on the Official API.
func (c networksClient) Get(ctx context.Context, siteId string, networkId string) (*NetworkDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s", url.PathEscape(siteId), url.PathEscape(networkId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed Get: %w", err)
	}
	return &out, nil
}

// GetReferences maps to GET /v1/sites/%s/networks/%s/references on the Official API.
func (c networksClient) GetReferences(ctx context.Context, siteId string, networkId string) (*NetworkReferences, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkReferences
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s/references", url.PathEscape(siteId), url.PathEscape(networkId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetReferences: %w", err)
	}
	return &out, nil
}

// List maps to GET /v1/sites/%s/networks on the Official API. Without options it auto-paginates the whole collection; pass WithOffset/WithLimit for a single bounded page or WithFilter to filter server-side.
func (c networksClient) List(ctx context.Context, siteId string, opts ...ListOption) ([]NetworkOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []NetworkOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/networks", url.PathEscape(siteId))), &out, opts...); err != nil {
		return nil, fmt.Errorf("failed List: %w", err)
	}
	return out, nil
}

// Update maps to PUT /v1/sites/%s/networks/%s on the Official API.
func (c networksClient) Update(ctx context.Context, siteId string, networkId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkDetails
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s", url.PathEscape(siteId), url.PathEscape(networkId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Update: %w", err)
	}
	return &out, nil
}

// NetworksClientMock is a func-field test double implementing NetworksClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type NetworksClientMock struct {
	CreateFunc        func(context.Context, string, NetworkCreateOrUpdate) (*NetworkDetails, error)
	DeleteFunc        func(context.Context, string, string) error
	GetFunc           func(context.Context, string, string) (*NetworkDetails, error)
	GetReferencesFunc func(context.Context, string, string) (*NetworkReferences, error)
	ListFunc          func(context.Context, string, ...ListOption) ([]NetworkOverview, error)
	UpdateFunc        func(context.Context, string, string, NetworkCreateOrUpdate) (*NetworkDetails, error)
}

var _ NetworksClient = (*NetworksClientMock)(nil)

func (m *NetworksClientMock) Create(ctx context.Context, siteId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	return m.CreateFunc(ctx, siteId, body)
}

func (m *NetworksClientMock) Delete(ctx context.Context, siteId string, networkId string) error {
	return m.DeleteFunc(ctx, siteId, networkId)
}

func (m *NetworksClientMock) Get(ctx context.Context, siteId string, networkId string) (*NetworkDetails, error) {
	return m.GetFunc(ctx, siteId, networkId)
}

func (m *NetworksClientMock) GetReferences(ctx context.Context, siteId string, networkId string) (*NetworkReferences, error) {
	return m.GetReferencesFunc(ctx, siteId, networkId)
}

func (m *NetworksClientMock) List(ctx context.Context, siteId string, opts ...ListOption) ([]NetworkOverview, error) {
	return m.ListFunc(ctx, siteId, opts...)
}

func (m *NetworksClientMock) Update(ctx context.Context, siteId string, networkId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	return m.UpdateFunc(ctx, siteId, networkId, body)
}
