// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// NetworksClient is the Networks resource group of the Official UniFi OpenAPI surface.
type NetworksClient interface {
	// Create maps to POST /v1/sites/%s/networks on the Official API.
	Create(ctx context.Context, siteId string, body NetworkCreateOrUpdate) (*NetworkDetails, error)
	// Delete maps to DELETE /v1/sites/%s/networks/%s on the Official API.
	Delete(ctx context.Context, siteId string, networkId string) error
	// GetDetails maps to GET /v1/sites/%s/networks/%s on the Official API.
	GetDetails(ctx context.Context, siteId string, networkId string) (*NetworkDetails, error)
	// GetOverviewPage maps to GET /v1/sites/%s/networks on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
	GetOverviewPage(ctx context.Context, siteId string) ([]NetworkOverview, error)
	// GetReferences maps to GET /v1/sites/%s/networks/%s/references on the Official API.
	GetReferences(ctx context.Context, siteId string, networkId string) (*NetworkReferences, error)
	// Update maps to PUT /v1/sites/%s/networks/%s on the Official API.
	Update(ctx context.Context, siteId string, networkId string, body NetworkCreateOrUpdate) (*NetworkDetails, error)
}

// networksClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type networksClient struct{ *apiClient }

var _ NetworksClient = networksClient{}

// Networks returns the Networks resource group.
func (c *apiClient) Networks() NetworksClient {
	return networksClient{c}
}

// Create maps to POST /v1/sites/%s/networks on the Official API.
func (c networksClient) Create(ctx context.Context, siteId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkDetails
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/networks", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Create: %w", err)
	}
	return &out, nil
}

// Delete maps to DELETE /v1/sites/%s/networks/%s on the Official API.
func (c networksClient) Delete(ctx context.Context, siteId string, networkId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s", url.PathEscape(siteId), url.PathEscape(networkId))), nil, nil); err != nil {
		return fmt.Errorf("failed Delete: %w", err)
	}
	return nil
}

// GetDetails maps to GET /v1/sites/%s/networks/%s on the Official API.
func (c networksClient) GetDetails(ctx context.Context, siteId string, networkId string) (*NetworkDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s", url.PathEscape(siteId), url.PathEscape(networkId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetDetails: %w", err)
	}
	return &out, nil
}

// GetOverviewPage maps to GET /v1/sites/%s/networks on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c networksClient) GetOverviewPage(ctx context.Context, siteId string) ([]NetworkOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []NetworkOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/networks", url.PathEscape(siteId))), &out); err != nil {
		return nil, fmt.Errorf("failed GetOverviewPage: %w", err)
	}
	return out, nil
}

// GetReferences maps to GET /v1/sites/%s/networks/%s/references on the Official API.
func (c networksClient) GetReferences(ctx context.Context, siteId string, networkId string) (*NetworkReferences, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkReferences
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s/references", url.PathEscape(siteId), url.PathEscape(networkId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetReferences: %w", err)
	}
	return &out, nil
}

// Update maps to PUT /v1/sites/%s/networks/%s on the Official API.
func (c networksClient) Update(ctx context.Context, siteId string, networkId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkDetails
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s", url.PathEscape(siteId), url.PathEscape(networkId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Update: %w", err)
	}
	return &out, nil
}

// NetworksClientMock is a func-field test double implementing NetworksClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type NetworksClientMock struct {
	CreateFunc          func(context.Context, string, NetworkCreateOrUpdate) (*NetworkDetails, error)
	DeleteFunc          func(context.Context, string, string) error
	GetDetailsFunc      func(context.Context, string, string) (*NetworkDetails, error)
	GetOverviewPageFunc func(context.Context, string) ([]NetworkOverview, error)
	GetReferencesFunc   func(context.Context, string, string) (*NetworkReferences, error)
	UpdateFunc          func(context.Context, string, string, NetworkCreateOrUpdate) (*NetworkDetails, error)
}

var _ NetworksClient = (*NetworksClientMock)(nil)

func (m *NetworksClientMock) Create(ctx context.Context, siteId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	return m.CreateFunc(ctx, siteId, body)
}

func (m *NetworksClientMock) Delete(ctx context.Context, siteId string, networkId string) error {
	return m.DeleteFunc(ctx, siteId, networkId)
}

func (m *NetworksClientMock) GetDetails(ctx context.Context, siteId string, networkId string) (*NetworkDetails, error) {
	return m.GetDetailsFunc(ctx, siteId, networkId)
}

func (m *NetworksClientMock) GetOverviewPage(ctx context.Context, siteId string) ([]NetworkOverview, error) {
	return m.GetOverviewPageFunc(ctx, siteId)
}

func (m *NetworksClientMock) GetReferences(ctx context.Context, siteId string, networkId string) (*NetworkReferences, error) {
	return m.GetReferencesFunc(ctx, siteId, networkId)
}

func (m *NetworksClientMock) Update(ctx context.Context, siteId string, networkId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	return m.UpdateFunc(ctx, siteId, networkId, body)
}
