// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"iter"
)

// SitesClient is the Sites resource group of the Official UniFi OpenAPI surface.
type SitesClient interface {
	// ListAll lazily drains every local site across pages.
	ListAll(ctx context.Context) iter.Seq2[SiteOverview, error]
	// ListPage returns one page of local sites; nil opts fetches the first page at the default size.
	ListPage(ctx context.Context, opts *ListOptions) (Page[SiteOverview], error)
	// ResolveID maps a legacy site name to its Official-API site UUID, caching the lookup.
	ResolveID(ctx context.Context, name string) (string, error)
}

// sitesClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type sitesClient struct{ *apiClient }

var _ SitesClient = sitesClient{}

// Sites returns the Sites resource group.
func (c *apiClient) Sites() SitesClient {
	return sitesClient{c}
}

// SitesClientMock is a func-field test double implementing SitesClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type SitesClientMock struct {
	ListAllFunc   func(context.Context) iter.Seq2[SiteOverview, error]
	ListPageFunc  func(context.Context, *ListOptions) (Page[SiteOverview], error)
	ResolveIDFunc func(context.Context, string) (string, error)
}

var _ SitesClient = (*SitesClientMock)(nil)

func (m *SitesClientMock) ListAll(ctx context.Context) iter.Seq2[SiteOverview, error] {
	return m.ListAllFunc(ctx)
}

func (m *SitesClientMock) ListPage(ctx context.Context, opts *ListOptions) (Page[SiteOverview], error) {
	return m.ListPageFunc(ctx, opts)
}

func (m *SitesClientMock) ResolveID(ctx context.Context, name string) (string, error) {
	return m.ResolveIDFunc(ctx, name)
}
