// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import "context"

// SitesClient is the Sites resource group of the Official UniFi OpenAPI surface.
type SitesClient interface {
	// List returns all local sites, auto-paginating the list envelope.
	List(ctx context.Context) ([]SiteOverview, error)
	// ResolveID maps a legacy site name to its Official-API site UUID, caching the lookup.
	ResolveID(ctx context.Context, name string) (string, error)
}

// sitesClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type sitesClient struct{ *apiClient }

var _ SitesClient = sitesClient{}

// Sites returns the Sites resource group.
func (c *apiClient) Sites() SitesClient {
	return sitesClient{c}
}

// SitesClientMock is a func-field test double implementing SitesClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type SitesClientMock struct {
	ListFunc      func(context.Context) ([]SiteOverview, error)
	ResolveIDFunc func(context.Context, string) (string, error)
}

var _ SitesClient = (*SitesClientMock)(nil)

func (m *SitesClientMock) List(ctx context.Context) ([]SiteOverview, error) {
	return m.ListFunc(ctx)
}

func (m *SitesClientMock) ResolveID(ctx context.Context, name string) (string, error) {
	return m.ResolveIDFunc(ctx, name)
}
