// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"iter"
	"net/url"
)

// SupportingClient is the Supporting resource group of the Official UniFi OpenAPI surface.
type SupportingClient interface {
	// ListCountriesAll lazily drains every item from GET /v1/countries, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListCountriesAll(ctx context.Context, filter string) iter.Seq2[CountryDefinition, error]
	// ListCountriesPage returns one page from GET /v1/countries; nil opts fetches the first page at the default size.
	ListCountriesPage(ctx context.Context, opts *ListOptions) (Page[CountryDefinition], error)
	// ListDeviceTagsAll lazily drains every item from GET /v1/sites/%s/device-tags, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListDeviceTagsAll(ctx context.Context, siteId string, filter string) iter.Seq2[DeviceTag, error]
	// ListDeviceTagsPage returns one page from GET /v1/sites/%s/device-tags; nil opts fetches the first page at the default size.
	ListDeviceTagsPage(ctx context.Context, siteId string, opts *ListOptions) (Page[DeviceTag], error)
	// ListDpiApplicationCategoriesAll lazily drains every item from GET /v1/dpi/categories, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListDpiApplicationCategoriesAll(ctx context.Context, filter string) iter.Seq2[DPICategory, error]
	// ListDpiApplicationCategoriesPage returns one page from GET /v1/dpi/categories; nil opts fetches the first page at the default size.
	ListDpiApplicationCategoriesPage(ctx context.Context, opts *ListOptions) (Page[DPICategory], error)
	// ListDpiApplicationsAll lazily drains every item from GET /v1/dpi/applications, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListDpiApplicationsAll(ctx context.Context, filter string) iter.Seq2[DPIApplication, error]
	// ListDpiApplicationsPage returns one page from GET /v1/dpi/applications; nil opts fetches the first page at the default size.
	ListDpiApplicationsPage(ctx context.Context, opts *ListOptions) (Page[DPIApplication], error)
	// ListRadiusProfilesAll lazily drains every item from GET /v1/sites/%s/radius/profiles, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListRadiusProfilesAll(ctx context.Context, siteId string, filter string) iter.Seq2[RadiusProfileOverview, error]
	// ListRadiusProfilesPage returns one page from GET /v1/sites/%s/radius/profiles; nil opts fetches the first page at the default size.
	ListRadiusProfilesPage(ctx context.Context, siteId string, opts *ListOptions) (Page[RadiusProfileOverview], error)
	// ListSiteToSiteVpnTunnelsAll lazily drains every item from GET /v1/sites/%s/vpn/site-to-site-tunnels, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListSiteToSiteVpnTunnelsAll(ctx context.Context, siteId string, filter string) iter.Seq2[SiteToSiteVPNTunnelOverview, error]
	// ListSiteToSiteVpnTunnelsPage returns one page from GET /v1/sites/%s/vpn/site-to-site-tunnels; nil opts fetches the first page at the default size.
	ListSiteToSiteVpnTunnelsPage(ctx context.Context, siteId string, opts *ListOptions) (Page[SiteToSiteVPNTunnelOverview], error)
	// ListVpnServersAll lazily drains every item from GET /v1/sites/%s/vpn/servers, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListVpnServersAll(ctx context.Context, siteId string, filter string) iter.Seq2[VPNServerOverview, error]
	// ListVpnServersPage returns one page from GET /v1/sites/%s/vpn/servers; nil opts fetches the first page at the default size.
	ListVpnServersPage(ctx context.Context, siteId string, opts *ListOptions) (Page[VPNServerOverview], error)
	// ListWansAll lazily drains every item from GET /v1/sites/%s/wans, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListWansAll(ctx context.Context, siteId string, filter string) iter.Seq2[WANOverview, error]
	// ListWansPage returns one page from GET /v1/sites/%s/wans; nil opts fetches the first page at the default size.
	ListWansPage(ctx context.Context, siteId string, opts *ListOptions) (Page[WANOverview], error)
}

// supportingClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type supportingClient struct{ *apiClient }

var _ SupportingClient = supportingClient{}

// Supporting returns the Supporting resource group.
func (c *apiClient) Supporting() SupportingClient {
	return supportingClient{c}
}

// ListCountriesAll lazily drains every item from GET /v1/countries, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c supportingClient) ListCountriesAll(ctx context.Context, filter string) iter.Seq2[CountryDefinition, error] {
	return listSeq[CountryDefinition](ctx, c.apiClient, c.path("/countries"), filter)
}

// ListCountriesPage returns one page from GET /v1/countries; nil opts fetches the first page at the default size.
func (c supportingClient) ListCountriesPage(ctx context.Context, opts *ListOptions) (Page[CountryDefinition], error) {
	if err := c.check(ctx); err != nil {
		return Page[CountryDefinition]{}, err
	}
	p, err := listPage[CountryDefinition](ctx, c.doer, c.path("/countries"), opts)
	if err != nil {
		return Page[CountryDefinition]{}, fmt.Errorf("failed ListCountriesPage: %w", err)
	}
	return p, nil
}

// ListDeviceTagsAll lazily drains every item from GET /v1/sites/%s/device-tags, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c supportingClient) ListDeviceTagsAll(ctx context.Context, siteId string, filter string) iter.Seq2[DeviceTag, error] {
	return listSeq[DeviceTag](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/device-tags", url.PathEscape(siteId))), filter)
}

// ListDeviceTagsPage returns one page from GET /v1/sites/%s/device-tags; nil opts fetches the first page at the default size.
func (c supportingClient) ListDeviceTagsPage(ctx context.Context, siteId string, opts *ListOptions) (Page[DeviceTag], error) {
	if err := c.check(ctx); err != nil {
		return Page[DeviceTag]{}, err
	}
	p, err := listPage[DeviceTag](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/device-tags", url.PathEscape(siteId))), opts)
	if err != nil {
		return Page[DeviceTag]{}, fmt.Errorf("failed ListDeviceTagsPage: %w", err)
	}
	return p, nil
}

// ListDpiApplicationCategoriesAll lazily drains every item from GET /v1/dpi/categories, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c supportingClient) ListDpiApplicationCategoriesAll(ctx context.Context, filter string) iter.Seq2[DPICategory, error] {
	return listSeq[DPICategory](ctx, c.apiClient, c.path("/dpi/categories"), filter)
}

// ListDpiApplicationCategoriesPage returns one page from GET /v1/dpi/categories; nil opts fetches the first page at the default size.
func (c supportingClient) ListDpiApplicationCategoriesPage(ctx context.Context, opts *ListOptions) (Page[DPICategory], error) {
	if err := c.check(ctx); err != nil {
		return Page[DPICategory]{}, err
	}
	p, err := listPage[DPICategory](ctx, c.doer, c.path("/dpi/categories"), opts)
	if err != nil {
		return Page[DPICategory]{}, fmt.Errorf("failed ListDpiApplicationCategoriesPage: %w", err)
	}
	return p, nil
}

// ListDpiApplicationsAll lazily drains every item from GET /v1/dpi/applications, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c supportingClient) ListDpiApplicationsAll(ctx context.Context, filter string) iter.Seq2[DPIApplication, error] {
	return listSeq[DPIApplication](ctx, c.apiClient, c.path("/dpi/applications"), filter)
}

// ListDpiApplicationsPage returns one page from GET /v1/dpi/applications; nil opts fetches the first page at the default size.
func (c supportingClient) ListDpiApplicationsPage(ctx context.Context, opts *ListOptions) (Page[DPIApplication], error) {
	if err := c.check(ctx); err != nil {
		return Page[DPIApplication]{}, err
	}
	p, err := listPage[DPIApplication](ctx, c.doer, c.path("/dpi/applications"), opts)
	if err != nil {
		return Page[DPIApplication]{}, fmt.Errorf("failed ListDpiApplicationsPage: %w", err)
	}
	return p, nil
}

// ListRadiusProfilesAll lazily drains every item from GET /v1/sites/%s/radius/profiles, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c supportingClient) ListRadiusProfilesAll(ctx context.Context, siteId string, filter string) iter.Seq2[RadiusProfileOverview, error] {
	return listSeq[RadiusProfileOverview](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/radius/profiles", url.PathEscape(siteId))), filter)
}

// ListRadiusProfilesPage returns one page from GET /v1/sites/%s/radius/profiles; nil opts fetches the first page at the default size.
func (c supportingClient) ListRadiusProfilesPage(ctx context.Context, siteId string, opts *ListOptions) (Page[RadiusProfileOverview], error) {
	if err := c.check(ctx); err != nil {
		return Page[RadiusProfileOverview]{}, err
	}
	p, err := listPage[RadiusProfileOverview](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/radius/profiles", url.PathEscape(siteId))), opts)
	if err != nil {
		return Page[RadiusProfileOverview]{}, fmt.Errorf("failed ListRadiusProfilesPage: %w", err)
	}
	return p, nil
}

// ListSiteToSiteVpnTunnelsAll lazily drains every item from GET /v1/sites/%s/vpn/site-to-site-tunnels, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c supportingClient) ListSiteToSiteVpnTunnelsAll(ctx context.Context, siteId string, filter string) iter.Seq2[SiteToSiteVPNTunnelOverview, error] {
	return listSeq[SiteToSiteVPNTunnelOverview](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/vpn/site-to-site-tunnels", url.PathEscape(siteId))), filter)
}

// ListSiteToSiteVpnTunnelsPage returns one page from GET /v1/sites/%s/vpn/site-to-site-tunnels; nil opts fetches the first page at the default size.
func (c supportingClient) ListSiteToSiteVpnTunnelsPage(ctx context.Context, siteId string, opts *ListOptions) (Page[SiteToSiteVPNTunnelOverview], error) {
	if err := c.check(ctx); err != nil {
		return Page[SiteToSiteVPNTunnelOverview]{}, err
	}
	p, err := listPage[SiteToSiteVPNTunnelOverview](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/vpn/site-to-site-tunnels", url.PathEscape(siteId))), opts)
	if err != nil {
		return Page[SiteToSiteVPNTunnelOverview]{}, fmt.Errorf("failed ListSiteToSiteVpnTunnelsPage: %w", err)
	}
	return p, nil
}

// ListVpnServersAll lazily drains every item from GET /v1/sites/%s/vpn/servers, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c supportingClient) ListVpnServersAll(ctx context.Context, siteId string, filter string) iter.Seq2[VPNServerOverview, error] {
	return listSeq[VPNServerOverview](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/vpn/servers", url.PathEscape(siteId))), filter)
}

// ListVpnServersPage returns one page from GET /v1/sites/%s/vpn/servers; nil opts fetches the first page at the default size.
func (c supportingClient) ListVpnServersPage(ctx context.Context, siteId string, opts *ListOptions) (Page[VPNServerOverview], error) {
	if err := c.check(ctx); err != nil {
		return Page[VPNServerOverview]{}, err
	}
	p, err := listPage[VPNServerOverview](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/vpn/servers", url.PathEscape(siteId))), opts)
	if err != nil {
		return Page[VPNServerOverview]{}, fmt.Errorf("failed ListVpnServersPage: %w", err)
	}
	return p, nil
}

// ListWansAll lazily drains every item from GET /v1/sites/%s/wans, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c supportingClient) ListWansAll(ctx context.Context, siteId string, filter string) iter.Seq2[WANOverview, error] {
	return listSeq[WANOverview](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/wans", url.PathEscape(siteId))), filter)
}

// ListWansPage returns one page from GET /v1/sites/%s/wans; nil opts fetches the first page at the default size.
func (c supportingClient) ListWansPage(ctx context.Context, siteId string, opts *ListOptions) (Page[WANOverview], error) {
	if err := c.check(ctx); err != nil {
		return Page[WANOverview]{}, err
	}
	p, err := listPage[WANOverview](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/wans", url.PathEscape(siteId))), opts)
	if err != nil {
		return Page[WANOverview]{}, fmt.Errorf("failed ListWansPage: %w", err)
	}
	return p, nil
}

// SupportingClientMock is a func-field test double implementing SupportingClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type SupportingClientMock struct {
	ListCountriesAllFunc                 func(context.Context, string) iter.Seq2[CountryDefinition, error]
	ListCountriesPageFunc                func(context.Context, *ListOptions) (Page[CountryDefinition], error)
	ListDeviceTagsAllFunc                func(context.Context, string, string) iter.Seq2[DeviceTag, error]
	ListDeviceTagsPageFunc               func(context.Context, string, *ListOptions) (Page[DeviceTag], error)
	ListDpiApplicationCategoriesAllFunc  func(context.Context, string) iter.Seq2[DPICategory, error]
	ListDpiApplicationCategoriesPageFunc func(context.Context, *ListOptions) (Page[DPICategory], error)
	ListDpiApplicationsAllFunc           func(context.Context, string) iter.Seq2[DPIApplication, error]
	ListDpiApplicationsPageFunc          func(context.Context, *ListOptions) (Page[DPIApplication], error)
	ListRadiusProfilesAllFunc            func(context.Context, string, string) iter.Seq2[RadiusProfileOverview, error]
	ListRadiusProfilesPageFunc           func(context.Context, string, *ListOptions) (Page[RadiusProfileOverview], error)
	ListSiteToSiteVpnTunnelsAllFunc      func(context.Context, string, string) iter.Seq2[SiteToSiteVPNTunnelOverview, error]
	ListSiteToSiteVpnTunnelsPageFunc     func(context.Context, string, *ListOptions) (Page[SiteToSiteVPNTunnelOverview], error)
	ListVpnServersAllFunc                func(context.Context, string, string) iter.Seq2[VPNServerOverview, error]
	ListVpnServersPageFunc               func(context.Context, string, *ListOptions) (Page[VPNServerOverview], error)
	ListWansAllFunc                      func(context.Context, string, string) iter.Seq2[WANOverview, error]
	ListWansPageFunc                     func(context.Context, string, *ListOptions) (Page[WANOverview], error)
}

var _ SupportingClient = (*SupportingClientMock)(nil)

func (m *SupportingClientMock) ListCountriesAll(ctx context.Context, filter string) iter.Seq2[CountryDefinition, error] {
	return m.ListCountriesAllFunc(ctx, filter)
}

func (m *SupportingClientMock) ListCountriesPage(ctx context.Context, opts *ListOptions) (Page[CountryDefinition], error) {
	return m.ListCountriesPageFunc(ctx, opts)
}

func (m *SupportingClientMock) ListDeviceTagsAll(ctx context.Context, siteId string, filter string) iter.Seq2[DeviceTag, error] {
	return m.ListDeviceTagsAllFunc(ctx, siteId, filter)
}

func (m *SupportingClientMock) ListDeviceTagsPage(ctx context.Context, siteId string, opts *ListOptions) (Page[DeviceTag], error) {
	return m.ListDeviceTagsPageFunc(ctx, siteId, opts)
}

func (m *SupportingClientMock) ListDpiApplicationCategoriesAll(ctx context.Context, filter string) iter.Seq2[DPICategory, error] {
	return m.ListDpiApplicationCategoriesAllFunc(ctx, filter)
}

func (m *SupportingClientMock) ListDpiApplicationCategoriesPage(ctx context.Context, opts *ListOptions) (Page[DPICategory], error) {
	return m.ListDpiApplicationCategoriesPageFunc(ctx, opts)
}

func (m *SupportingClientMock) ListDpiApplicationsAll(ctx context.Context, filter string) iter.Seq2[DPIApplication, error] {
	return m.ListDpiApplicationsAllFunc(ctx, filter)
}

func (m *SupportingClientMock) ListDpiApplicationsPage(ctx context.Context, opts *ListOptions) (Page[DPIApplication], error) {
	return m.ListDpiApplicationsPageFunc(ctx, opts)
}

func (m *SupportingClientMock) ListRadiusProfilesAll(ctx context.Context, siteId string, filter string) iter.Seq2[RadiusProfileOverview, error] {
	return m.ListRadiusProfilesAllFunc(ctx, siteId, filter)
}

func (m *SupportingClientMock) ListRadiusProfilesPage(ctx context.Context, siteId string, opts *ListOptions) (Page[RadiusProfileOverview], error) {
	return m.ListRadiusProfilesPageFunc(ctx, siteId, opts)
}

func (m *SupportingClientMock) ListSiteToSiteVpnTunnelsAll(ctx context.Context, siteId string, filter string) iter.Seq2[SiteToSiteVPNTunnelOverview, error] {
	return m.ListSiteToSiteVpnTunnelsAllFunc(ctx, siteId, filter)
}

func (m *SupportingClientMock) ListSiteToSiteVpnTunnelsPage(ctx context.Context, siteId string, opts *ListOptions) (Page[SiteToSiteVPNTunnelOverview], error) {
	return m.ListSiteToSiteVpnTunnelsPageFunc(ctx, siteId, opts)
}

func (m *SupportingClientMock) ListVpnServersAll(ctx context.Context, siteId string, filter string) iter.Seq2[VPNServerOverview, error] {
	return m.ListVpnServersAllFunc(ctx, siteId, filter)
}

func (m *SupportingClientMock) ListVpnServersPage(ctx context.Context, siteId string, opts *ListOptions) (Page[VPNServerOverview], error) {
	return m.ListVpnServersPageFunc(ctx, siteId, opts)
}

func (m *SupportingClientMock) ListWansAll(ctx context.Context, siteId string, filter string) iter.Seq2[WANOverview, error] {
	return m.ListWansAllFunc(ctx, siteId, filter)
}

func (m *SupportingClientMock) ListWansPage(ctx context.Context, siteId string, opts *ListOptions) (Page[WANOverview], error) {
	return m.ListWansPageFunc(ctx, siteId, opts)
}
