// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"iter"

	"github.com/google/uuid"
)

// SwitchingClient is the Switching resource group of the Official UniFi OpenAPI surface.
type SwitchingClient interface {
	// GetLag maps to GET /v1/sites/%s/switching/lags/%s on the Official API.
	GetLag(ctx context.Context, siteId uuid.UUID, lagId uuid.UUID) (*LAGDetails, error)
	// GetMcLagDomain maps to GET /v1/sites/%s/switching/mc-lag-domains/%s on the Official API.
	GetMcLagDomain(ctx context.Context, siteId uuid.UUID, mcLagDomainId uuid.UUID) (*McLagDomain, error)
	// GetSwitchStack maps to GET /v1/sites/%s/switching/switch-stacks/%s on the Official API.
	GetSwitchStack(ctx context.Context, siteId uuid.UUID, switchStackId uuid.UUID) (*SwitchStack, error)
	// ListLagsAll lazily drains every item from GET /v1/sites/%s/switching/lags, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListLagsAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[LAGDetails, error]
	// ListLagsPage returns one page from GET /v1/sites/%s/switching/lags; nil opts fetches the first page at the default size.
	ListLagsPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[LAGDetails], error)
	// ListMcLagDomainsAll lazily drains every item from GET /v1/sites/%s/switching/mc-lag-domains, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListMcLagDomainsAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[McLagDomain, error]
	// ListMcLagDomainsPage returns one page from GET /v1/sites/%s/switching/mc-lag-domains; nil opts fetches the first page at the default size.
	ListMcLagDomainsPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[McLagDomain], error)
	// ListSwitchStacksAll lazily drains every item from GET /v1/sites/%s/switching/switch-stacks, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListSwitchStacksAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[SwitchStack, error]
	// ListSwitchStacksPage returns one page from GET /v1/sites/%s/switching/switch-stacks; nil opts fetches the first page at the default size.
	ListSwitchStacksPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[SwitchStack], error)
}

// switchingClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type switchingClient struct{ *apiClient }

var _ SwitchingClient = switchingClient{}

// Switching returns the Switching resource group.
func (c *apiClient) Switching() SwitchingClient {
	return switchingClient{c}
}

// GetLag maps to GET /v1/sites/%s/switching/lags/%s on the Official API.
func (c switchingClient) GetLag(ctx context.Context, siteId uuid.UUID, lagId uuid.UUID) (*LAGDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out LAGDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/switching/lags/%s", siteId.String(), lagId.String())), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetLag: %w", err)
	}
	return &out, nil
}

// GetMcLagDomain maps to GET /v1/sites/%s/switching/mc-lag-domains/%s on the Official API.
func (c switchingClient) GetMcLagDomain(ctx context.Context, siteId uuid.UUID, mcLagDomainId uuid.UUID) (*McLagDomain, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out McLagDomain
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/switching/mc-lag-domains/%s", siteId.String(), mcLagDomainId.String())), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetMcLagDomain: %w", err)
	}
	return &out, nil
}

// GetSwitchStack maps to GET /v1/sites/%s/switching/switch-stacks/%s on the Official API.
func (c switchingClient) GetSwitchStack(ctx context.Context, siteId uuid.UUID, switchStackId uuid.UUID) (*SwitchStack, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out SwitchStack
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/switching/switch-stacks/%s", siteId.String(), switchStackId.String())), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetSwitchStack: %w", err)
	}
	return &out, nil
}

// ListLagsAll lazily drains every item from GET /v1/sites/%s/switching/lags, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c switchingClient) ListLagsAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[LAGDetails, error] {
	return listSeq[LAGDetails](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/switching/lags", siteId.String())), filter)
}

// ListLagsPage returns one page from GET /v1/sites/%s/switching/lags; nil opts fetches the first page at the default size.
func (c switchingClient) ListLagsPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[LAGDetails], error) {
	if err := c.check(ctx); err != nil {
		return Page[LAGDetails]{}, err
	}
	p, err := listPage[LAGDetails](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/switching/lags", siteId.String())), opts)
	if err != nil {
		return Page[LAGDetails]{}, fmt.Errorf("failed ListLagsPage: %w", err)
	}
	return p, nil
}

// ListMcLagDomainsAll lazily drains every item from GET /v1/sites/%s/switching/mc-lag-domains, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c switchingClient) ListMcLagDomainsAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[McLagDomain, error] {
	return listSeq[McLagDomain](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/switching/mc-lag-domains", siteId.String())), filter)
}

// ListMcLagDomainsPage returns one page from GET /v1/sites/%s/switching/mc-lag-domains; nil opts fetches the first page at the default size.
func (c switchingClient) ListMcLagDomainsPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[McLagDomain], error) {
	if err := c.check(ctx); err != nil {
		return Page[McLagDomain]{}, err
	}
	p, err := listPage[McLagDomain](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/switching/mc-lag-domains", siteId.String())), opts)
	if err != nil {
		return Page[McLagDomain]{}, fmt.Errorf("failed ListMcLagDomainsPage: %w", err)
	}
	return p, nil
}

// ListSwitchStacksAll lazily drains every item from GET /v1/sites/%s/switching/switch-stacks, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c switchingClient) ListSwitchStacksAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[SwitchStack, error] {
	return listSeq[SwitchStack](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/switching/switch-stacks", siteId.String())), filter)
}

// ListSwitchStacksPage returns one page from GET /v1/sites/%s/switching/switch-stacks; nil opts fetches the first page at the default size.
func (c switchingClient) ListSwitchStacksPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[SwitchStack], error) {
	if err := c.check(ctx); err != nil {
		return Page[SwitchStack]{}, err
	}
	p, err := listPage[SwitchStack](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/switching/switch-stacks", siteId.String())), opts)
	if err != nil {
		return Page[SwitchStack]{}, fmt.Errorf("failed ListSwitchStacksPage: %w", err)
	}
	return p, nil
}

// SwitchingClientMock is a func-field test double implementing SwitchingClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type SwitchingClientMock struct {
	GetLagFunc               func(context.Context, uuid.UUID, uuid.UUID) (*LAGDetails, error)
	GetMcLagDomainFunc       func(context.Context, uuid.UUID, uuid.UUID) (*McLagDomain, error)
	GetSwitchStackFunc       func(context.Context, uuid.UUID, uuid.UUID) (*SwitchStack, error)
	ListLagsAllFunc          func(context.Context, uuid.UUID, string) iter.Seq2[LAGDetails, error]
	ListLagsPageFunc         func(context.Context, uuid.UUID, *ListOptions) (Page[LAGDetails], error)
	ListMcLagDomainsAllFunc  func(context.Context, uuid.UUID, string) iter.Seq2[McLagDomain, error]
	ListMcLagDomainsPageFunc func(context.Context, uuid.UUID, *ListOptions) (Page[McLagDomain], error)
	ListSwitchStacksAllFunc  func(context.Context, uuid.UUID, string) iter.Seq2[SwitchStack, error]
	ListSwitchStacksPageFunc func(context.Context, uuid.UUID, *ListOptions) (Page[SwitchStack], error)
}

var _ SwitchingClient = (*SwitchingClientMock)(nil)

func (m *SwitchingClientMock) GetLag(ctx context.Context, siteId uuid.UUID, lagId uuid.UUID) (*LAGDetails, error) {
	return m.GetLagFunc(ctx, siteId, lagId)
}

func (m *SwitchingClientMock) GetMcLagDomain(ctx context.Context, siteId uuid.UUID, mcLagDomainId uuid.UUID) (*McLagDomain, error) {
	return m.GetMcLagDomainFunc(ctx, siteId, mcLagDomainId)
}

func (m *SwitchingClientMock) GetSwitchStack(ctx context.Context, siteId uuid.UUID, switchStackId uuid.UUID) (*SwitchStack, error) {
	return m.GetSwitchStackFunc(ctx, siteId, switchStackId)
}

func (m *SwitchingClientMock) ListLagsAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[LAGDetails, error] {
	return m.ListLagsAllFunc(ctx, siteId, filter)
}

func (m *SwitchingClientMock) ListLagsPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[LAGDetails], error) {
	return m.ListLagsPageFunc(ctx, siteId, opts)
}

func (m *SwitchingClientMock) ListMcLagDomainsAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[McLagDomain, error] {
	return m.ListMcLagDomainsAllFunc(ctx, siteId, filter)
}

func (m *SwitchingClientMock) ListMcLagDomainsPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[McLagDomain], error) {
	return m.ListMcLagDomainsPageFunc(ctx, siteId, opts)
}

func (m *SwitchingClientMock) ListSwitchStacksAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[SwitchStack, error] {
	return m.ListSwitchStacksAllFunc(ctx, siteId, filter)
}

func (m *SwitchingClientMock) ListSwitchStacksPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[SwitchStack], error) {
	return m.ListSwitchStacksPageFunc(ctx, siteId, opts)
}
