// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"iter"

	"github.com/google/uuid"
)

// TrafficMatchingListsClient is the TrafficMatchingLists resource group of the Official UniFi OpenAPI surface.
type TrafficMatchingListsClient interface {
	// Create maps to POST /v1/sites/%s/traffic-matching-lists on the Official API.
	Create(ctx context.Context, siteId uuid.UUID, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
	// Delete maps to DELETE /v1/sites/%s/traffic-matching-lists/%s on the Official API.
	Delete(ctx context.Context, siteId uuid.UUID, trafficMatchingListId uuid.UUID) error
	// Get maps to GET /v1/sites/%s/traffic-matching-lists/%s on the Official API.
	Get(ctx context.Context, siteId uuid.UUID, trafficMatchingListId uuid.UUID) (*TrafficMatchingList, error)
	// ListAll lazily drains every item from GET /v1/sites/%s/traffic-matching-lists, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
	ListAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[TrafficMatchingList, error]
	// ListPage returns one page from GET /v1/sites/%s/traffic-matching-lists; nil opts fetches the first page at the default size.
	ListPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[TrafficMatchingList], error)
	// Update maps to PUT /v1/sites/%s/traffic-matching-lists/%s on the Official API.
	Update(ctx context.Context, siteId uuid.UUID, trafficMatchingListId uuid.UUID, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
}

// trafficMatchingListsClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type trafficMatchingListsClient struct{ *apiClient }

var _ TrafficMatchingListsClient = trafficMatchingListsClient{}

// TrafficMatchingLists returns the TrafficMatchingLists resource group.
func (c *apiClient) TrafficMatchingLists() TrafficMatchingListsClient {
	return trafficMatchingListsClient{c}
}

// Create maps to POST /v1/sites/%s/traffic-matching-lists on the Official API.
func (c trafficMatchingListsClient) Create(ctx context.Context, siteId uuid.UUID, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists", siteId.String())), body, &out); err != nil {
		return nil, fmt.Errorf("failed Create: %w", err)
	}
	return &out, nil
}

// Delete maps to DELETE /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c trafficMatchingListsClient) Delete(ctx context.Context, siteId uuid.UUID, trafficMatchingListId uuid.UUID) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", siteId.String(), trafficMatchingListId.String())), nil, nil); err != nil {
		return fmt.Errorf("failed Delete: %w", err)
	}
	return nil
}

// Get maps to GET /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c trafficMatchingListsClient) Get(ctx context.Context, siteId uuid.UUID, trafficMatchingListId uuid.UUID) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", siteId.String(), trafficMatchingListId.String())), nil, &out); err != nil {
		return nil, fmt.Errorf("failed Get: %w", err)
	}
	return &out, nil
}

// ListAll lazily drains every item from GET /v1/sites/%s/traffic-matching-lists, paging on demand; pass "" filter to drain unfiltered; range it and break to stop early.
func (c trafficMatchingListsClient) ListAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[TrafficMatchingList, error] {
	return listSeq[TrafficMatchingList](ctx, c.apiClient, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists", siteId.String())), filter)
}

// ListPage returns one page from GET /v1/sites/%s/traffic-matching-lists; nil opts fetches the first page at the default size.
func (c trafficMatchingListsClient) ListPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[TrafficMatchingList], error) {
	if err := c.check(ctx); err != nil {
		return Page[TrafficMatchingList]{}, err
	}
	p, err := listPage[TrafficMatchingList](ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists", siteId.String())), opts)
	if err != nil {
		return Page[TrafficMatchingList]{}, fmt.Errorf("failed ListPage: %w", err)
	}
	return p, nil
}

// Update maps to PUT /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c trafficMatchingListsClient) Update(ctx context.Context, siteId uuid.UUID, trafficMatchingListId uuid.UUID, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", siteId.String(), trafficMatchingListId.String())), body, &out); err != nil {
		return nil, fmt.Errorf("failed Update: %w", err)
	}
	return &out, nil
}

// TrafficMatchingListsClientMock is a func-field test double implementing TrafficMatchingListsClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type TrafficMatchingListsClientMock struct {
	CreateFunc   func(context.Context, uuid.UUID, TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
	DeleteFunc   func(context.Context, uuid.UUID, uuid.UUID) error
	GetFunc      func(context.Context, uuid.UUID, uuid.UUID) (*TrafficMatchingList, error)
	ListAllFunc  func(context.Context, uuid.UUID, string) iter.Seq2[TrafficMatchingList, error]
	ListPageFunc func(context.Context, uuid.UUID, *ListOptions) (Page[TrafficMatchingList], error)
	UpdateFunc   func(context.Context, uuid.UUID, uuid.UUID, TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
}

var _ TrafficMatchingListsClient = (*TrafficMatchingListsClientMock)(nil)

func (m *TrafficMatchingListsClientMock) Create(ctx context.Context, siteId uuid.UUID, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	return m.CreateFunc(ctx, siteId, body)
}

func (m *TrafficMatchingListsClientMock) Delete(ctx context.Context, siteId uuid.UUID, trafficMatchingListId uuid.UUID) error {
	return m.DeleteFunc(ctx, siteId, trafficMatchingListId)
}

func (m *TrafficMatchingListsClientMock) Get(ctx context.Context, siteId uuid.UUID, trafficMatchingListId uuid.UUID) (*TrafficMatchingList, error) {
	return m.GetFunc(ctx, siteId, trafficMatchingListId)
}

func (m *TrafficMatchingListsClientMock) ListAll(ctx context.Context, siteId uuid.UUID, filter string) iter.Seq2[TrafficMatchingList, error] {
	return m.ListAllFunc(ctx, siteId, filter)
}

func (m *TrafficMatchingListsClientMock) ListPage(ctx context.Context, siteId uuid.UUID, opts *ListOptions) (Page[TrafficMatchingList], error) {
	return m.ListPageFunc(ctx, siteId, opts)
}

func (m *TrafficMatchingListsClientMock) Update(ctx context.Context, siteId uuid.UUID, trafficMatchingListId uuid.UUID, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	return m.UpdateFunc(ctx, siteId, trafficMatchingListId, body)
}
