// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// TrafficMatchingListsClient is the TrafficMatchingLists resource group of the Official UniFi OpenAPI surface.
type TrafficMatchingListsClient interface {
	// Create maps to POST /v1/sites/%s/traffic-matching-lists on the Official API.
	Create(ctx context.Context, siteId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
	// Delete maps to DELETE /v1/sites/%s/traffic-matching-lists/%s on the Official API.
	Delete(ctx context.Context, siteId string, trafficMatchingListId string) error
	// Get maps to GET /v1/sites/%s/traffic-matching-lists/%s on the Official API.
	Get(ctx context.Context, siteId string, trafficMatchingListId string) (*TrafficMatchingList, error)
	// GetLists maps to GET /v1/sites/%s/traffic-matching-lists on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
	GetLists(ctx context.Context, siteId string) ([]TrafficMatchingList, error)
	// Update maps to PUT /v1/sites/%s/traffic-matching-lists/%s on the Official API.
	Update(ctx context.Context, siteId string, trafficMatchingListId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
}

// trafficMatchingListsClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type trafficMatchingListsClient struct{ *apiClient }

var _ TrafficMatchingListsClient = trafficMatchingListsClient{}

// TrafficMatchingLists returns the TrafficMatchingLists resource group.
func (c *apiClient) TrafficMatchingLists() TrafficMatchingListsClient {
	return trafficMatchingListsClient{c}
}

// Create maps to POST /v1/sites/%s/traffic-matching-lists on the Official API.
func (c trafficMatchingListsClient) Create(ctx context.Context, siteId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Create: %w", err)
	}
	return &out, nil
}

// Delete maps to DELETE /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c trafficMatchingListsClient) Delete(ctx context.Context, siteId string, trafficMatchingListId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", url.PathEscape(siteId), url.PathEscape(trafficMatchingListId))), nil, nil); err != nil {
		return fmt.Errorf("failed Delete: %w", err)
	}
	return nil
}

// Get maps to GET /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c trafficMatchingListsClient) Get(ctx context.Context, siteId string, trafficMatchingListId string) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", url.PathEscape(siteId), url.PathEscape(trafficMatchingListId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed Get: %w", err)
	}
	return &out, nil
}

// GetLists maps to GET /v1/sites/%s/traffic-matching-lists on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c trafficMatchingListsClient) GetLists(ctx context.Context, siteId string) ([]TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []TrafficMatchingList
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists", url.PathEscape(siteId))), &out); err != nil {
		return nil, fmt.Errorf("failed GetLists: %w", err)
	}
	return out, nil
}

// Update maps to PUT /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c trafficMatchingListsClient) Update(ctx context.Context, siteId string, trafficMatchingListId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", url.PathEscape(siteId), url.PathEscape(trafficMatchingListId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Update: %w", err)
	}
	return &out, nil
}

// TrafficMatchingListsClientMock is a func-field test double implementing TrafficMatchingListsClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type TrafficMatchingListsClientMock struct {
	CreateFunc   func(context.Context, string, TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
	DeleteFunc   func(context.Context, string, string) error
	GetFunc      func(context.Context, string, string) (*TrafficMatchingList, error)
	GetListsFunc func(context.Context, string) ([]TrafficMatchingList, error)
	UpdateFunc   func(context.Context, string, string, TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
}

var _ TrafficMatchingListsClient = (*TrafficMatchingListsClientMock)(nil)

func (m *TrafficMatchingListsClientMock) Create(ctx context.Context, siteId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	return m.CreateFunc(ctx, siteId, body)
}

func (m *TrafficMatchingListsClientMock) Delete(ctx context.Context, siteId string, trafficMatchingListId string) error {
	return m.DeleteFunc(ctx, siteId, trafficMatchingListId)
}

func (m *TrafficMatchingListsClientMock) Get(ctx context.Context, siteId string, trafficMatchingListId string) (*TrafficMatchingList, error) {
	return m.GetFunc(ctx, siteId, trafficMatchingListId)
}

func (m *TrafficMatchingListsClientMock) GetLists(ctx context.Context, siteId string) ([]TrafficMatchingList, error) {
	return m.GetListsFunc(ctx, siteId)
}

func (m *TrafficMatchingListsClientMock) Update(ctx context.Context, siteId string, trafficMatchingListId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	return m.UpdateFunc(ctx, siteId, trafficMatchingListId, body)
}
