// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// TrafficMatchingClient is the TrafficMatching resource group of the Official UniFi OpenAPI surface.
type TrafficMatchingClient interface {
	// CreateList maps to POST /v1/sites/%s/traffic-matching-lists on the Official API.
	CreateList(ctx context.Context, siteId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
	// DeleteList maps to DELETE /v1/sites/%s/traffic-matching-lists/%s on the Official API.
	DeleteList(ctx context.Context, siteId string, trafficMatchingListId string) error
	// GetList maps to GET /v1/sites/%s/traffic-matching-lists/%s on the Official API.
	GetList(ctx context.Context, siteId string, trafficMatchingListId string) (*TrafficMatchingList, error)
	// GetLists maps to GET /v1/sites/%s/traffic-matching-lists on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
	GetLists(ctx context.Context, siteId string) ([]TrafficMatchingList, error)
	// UpdateList maps to PUT /v1/sites/%s/traffic-matching-lists/%s on the Official API.
	UpdateList(ctx context.Context, siteId string, trafficMatchingListId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
}

// trafficMatchingClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type trafficMatchingClient struct{ *apiClient }

var _ TrafficMatchingClient = trafficMatchingClient{}

// TrafficMatching returns the TrafficMatching resource group.
func (c *apiClient) TrafficMatching() TrafficMatchingClient {
	return trafficMatchingClient{c}
}

// CreateList maps to POST /v1/sites/%s/traffic-matching-lists on the Official API.
func (c trafficMatchingClient) CreateList(ctx context.Context, siteId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateList: %w", err)
	}
	return &out, nil
}

// DeleteList maps to DELETE /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c trafficMatchingClient) DeleteList(ctx context.Context, siteId string, trafficMatchingListId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", url.PathEscape(siteId), url.PathEscape(trafficMatchingListId))), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteList: %w", err)
	}
	return nil
}

// GetList maps to GET /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c trafficMatchingClient) GetList(ctx context.Context, siteId string, trafficMatchingListId string) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", url.PathEscape(siteId), url.PathEscape(trafficMatchingListId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetList: %w", err)
	}
	return &out, nil
}

// GetLists maps to GET /v1/sites/%s/traffic-matching-lists on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c trafficMatchingClient) GetLists(ctx context.Context, siteId string) ([]TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []TrafficMatchingList
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists", url.PathEscape(siteId))), &out); err != nil {
		return nil, fmt.Errorf("failed GetLists: %w", err)
	}
	return out, nil
}

// UpdateList maps to PUT /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c trafficMatchingClient) UpdateList(ctx context.Context, siteId string, trafficMatchingListId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", url.PathEscape(siteId), url.PathEscape(trafficMatchingListId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateList: %w", err)
	}
	return &out, nil
}

// TrafficMatchingClientMock is a func-field test double implementing TrafficMatchingClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type TrafficMatchingClientMock struct {
	CreateListFunc func(context.Context, string, TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
	DeleteListFunc func(context.Context, string, string) error
	GetListFunc    func(context.Context, string, string) (*TrafficMatchingList, error)
	GetListsFunc   func(context.Context, string) ([]TrafficMatchingList, error)
	UpdateListFunc func(context.Context, string, string, TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error)
}

var _ TrafficMatchingClient = (*TrafficMatchingClientMock)(nil)

func (m *TrafficMatchingClientMock) CreateList(ctx context.Context, siteId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	return m.CreateListFunc(ctx, siteId, body)
}

func (m *TrafficMatchingClientMock) DeleteList(ctx context.Context, siteId string, trafficMatchingListId string) error {
	return m.DeleteListFunc(ctx, siteId, trafficMatchingListId)
}

func (m *TrafficMatchingClientMock) GetList(ctx context.Context, siteId string, trafficMatchingListId string) (*TrafficMatchingList, error) {
	return m.GetListFunc(ctx, siteId, trafficMatchingListId)
}

func (m *TrafficMatchingClientMock) GetLists(ctx context.Context, siteId string) ([]TrafficMatchingList, error) {
	return m.GetListsFunc(ctx, siteId)
}

func (m *TrafficMatchingClientMock) UpdateList(ctx context.Context, siteId string, trafficMatchingListId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	return m.UpdateListFunc(ctx, siteId, trafficMatchingListId, body)
}
