// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"fmt"
	"net/url"
)

// WifiBroadcastsClient is the WifiBroadcasts resource group of the Official UniFi OpenAPI surface.
type WifiBroadcastsClient interface {
	// Create maps to POST /v1/sites/%s/wifi/broadcasts on the Official API.
	Create(ctx context.Context, siteId string, body WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error)
	// Delete maps to DELETE /v1/sites/%s/wifi/broadcasts/%s on the Official API.
	Delete(ctx context.Context, siteId string, wifiBroadcastId string) error
	// GetDetails maps to GET /v1/sites/%s/wifi/broadcasts/%s on the Official API.
	GetDetails(ctx context.Context, siteId string, wifiBroadcastId string) (*WifiBroadcastDetails, error)
	// GetPage maps to GET /v1/sites/%s/wifi/broadcasts on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
	GetPage(ctx context.Context, siteId string) ([]WifiBroadcastOverview, error)
	// Update maps to PUT /v1/sites/%s/wifi/broadcasts/%s on the Official API.
	Update(ctx context.Context, siteId string, wifiBroadcastId string, body WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error)
}

// wifiBroadcastsClient wraps the shared apiClient so transport, gate and site cache stay single-sourced.
type wifiBroadcastsClient struct{ *apiClient }

var _ WifiBroadcastsClient = wifiBroadcastsClient{}

// WifiBroadcasts returns the WifiBroadcasts resource group.
func (c *apiClient) WifiBroadcasts() WifiBroadcastsClient {
	return wifiBroadcastsClient{c}
}

// Create maps to POST /v1/sites/%s/wifi/broadcasts on the Official API.
func (c wifiBroadcastsClient) Create(ctx context.Context, siteId string, body WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out WifiBroadcastDetails
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/wifi/broadcasts", url.PathEscape(siteId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Create: %w", err)
	}
	return &out, nil
}

// Delete maps to DELETE /v1/sites/%s/wifi/broadcasts/%s on the Official API.
func (c wifiBroadcastsClient) Delete(ctx context.Context, siteId string, wifiBroadcastId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/wifi/broadcasts/%s", url.PathEscape(siteId), url.PathEscape(wifiBroadcastId))), nil, nil); err != nil {
		return fmt.Errorf("failed Delete: %w", err)
	}
	return nil
}

// GetDetails maps to GET /v1/sites/%s/wifi/broadcasts/%s on the Official API.
func (c wifiBroadcastsClient) GetDetails(ctx context.Context, siteId string, wifiBroadcastId string) (*WifiBroadcastDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out WifiBroadcastDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/wifi/broadcasts/%s", url.PathEscape(siteId), url.PathEscape(wifiBroadcastId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetDetails: %w", err)
	}
	return &out, nil
}

// GetPage maps to GET /v1/sites/%s/wifi/broadcasts on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c wifiBroadcastsClient) GetPage(ctx context.Context, siteId string) ([]WifiBroadcastOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []WifiBroadcastOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/wifi/broadcasts", url.PathEscape(siteId))), &out); err != nil {
		return nil, fmt.Errorf("failed GetPage: %w", err)
	}
	return out, nil
}

// Update maps to PUT /v1/sites/%s/wifi/broadcasts/%s on the Official API.
func (c wifiBroadcastsClient) Update(ctx context.Context, siteId string, wifiBroadcastId string, body WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out WifiBroadcastDetails
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/wifi/broadcasts/%s", url.PathEscape(siteId), url.PathEscape(wifiBroadcastId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed Update: %w", err)
	}
	return &out, nil
}

// WifiBroadcastsClientMock is a func-field test double implementing WifiBroadcastsClient. A nil field
// panics on call, surfacing an un-stubbed method in tests.
type WifiBroadcastsClientMock struct {
	CreateFunc     func(context.Context, string, WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error)
	DeleteFunc     func(context.Context, string, string) error
	GetDetailsFunc func(context.Context, string, string) (*WifiBroadcastDetails, error)
	GetPageFunc    func(context.Context, string) ([]WifiBroadcastOverview, error)
	UpdateFunc     func(context.Context, string, string, WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error)
}

var _ WifiBroadcastsClient = (*WifiBroadcastsClientMock)(nil)

func (m *WifiBroadcastsClientMock) Create(ctx context.Context, siteId string, body WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error) {
	return m.CreateFunc(ctx, siteId, body)
}

func (m *WifiBroadcastsClientMock) Delete(ctx context.Context, siteId string, wifiBroadcastId string) error {
	return m.DeleteFunc(ctx, siteId, wifiBroadcastId)
}

func (m *WifiBroadcastsClientMock) GetDetails(ctx context.Context, siteId string, wifiBroadcastId string) (*WifiBroadcastDetails, error) {
	return m.GetDetailsFunc(ctx, siteId, wifiBroadcastId)
}

func (m *WifiBroadcastsClientMock) GetPage(ctx context.Context, siteId string) ([]WifiBroadcastOverview, error) {
	return m.GetPageFunc(ctx, siteId)
}

func (m *WifiBroadcastsClientMock) Update(ctx context.Context, siteId string, wifiBroadcastId string, body WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error) {
	return m.UpdateFunc(ctx, siteId, wifiBroadcastId, body)
}
