// Code generated by github.com/filipowm/go-unifi/codegen/official version (devel) DO NOT EDIT.

package official

import (
	"context"
	"errors"
	"fmt"
	"net/url"
)

// AdoptDevice maps to POST /v1/sites/%s/devices on the Official API.
func (c *apiClient) AdoptDevice(ctx context.Context, siteId string, body DeviceAdoptionRequest) (*AdoptedDeviceDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out AdoptedDeviceDetails
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices", siteId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed AdoptDevice: %w", err)
	}
	return &out, nil
}

// CreateAclRule maps to POST /v1/sites/%s/acl-rules on the Official API.
func (c *apiClient) CreateAclRule(ctx context.Context, siteId string, body ACLRuleUpdate) (*ACLRule, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRule
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules", siteId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateAclRule: %w", err)
	}
	return &out, nil
}

// CreateDnsPolicy maps to POST /v1/sites/%s/dns/policies on the Official API.
func (c *apiClient) CreateDnsPolicy(ctx context.Context, siteId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out DNSPolicy
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies", siteId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateDnsPolicy: %w", err)
	}
	return &out, nil
}

// CreateFirewallPolicy maps to POST /v1/sites/%s/firewall/policies on the Official API.
func (c *apiClient) CreateFirewallPolicy(ctx context.Context, siteId string, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies", siteId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateFirewallPolicy: %w", err)
	}
	return &out, nil
}

// CreateFirewallZone maps to POST /v1/sites/%s/firewall/zones on the Official API.
func (c *apiClient) CreateFirewallZone(ctx context.Context, siteId string, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallZone
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones", siteId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateFirewallZone: %w", err)
	}
	return &out, nil
}

// CreateNetwork maps to POST /v1/sites/%s/networks on the Official API.
func (c *apiClient) CreateNetwork(ctx context.Context, siteId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkDetails
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/networks", siteId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateNetwork: %w", err)
	}
	return &out, nil
}

// CreateTrafficMatchingList maps to POST /v1/sites/%s/traffic-matching-lists on the Official API.
func (c *apiClient) CreateTrafficMatchingList(ctx context.Context, siteId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists", siteId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateTrafficMatchingList: %w", err)
	}
	return &out, nil
}

// CreateVouchers maps to POST /v1/sites/%s/hotspot/vouchers on the Official API.
func (c *apiClient) CreateVouchers(ctx context.Context, siteId string, body HotspotVoucherCreationRequest) (*VoucherCreationResult, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out VoucherCreationResult
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/hotspot/vouchers", siteId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateVouchers: %w", err)
	}
	return &out, nil
}

// CreateWifiBroadcast maps to POST /v1/sites/%s/wifi/broadcasts on the Official API.
func (c *apiClient) CreateWifiBroadcast(ctx context.Context, siteId string, body WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out WifiBroadcastDetails
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/wifi/broadcasts", siteId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed CreateWifiBroadcast: %w", err)
	}
	return &out, nil
}

// DeleteAclRule maps to DELETE /v1/sites/%s/acl-rules/%s on the Official API.
func (c *apiClient) DeleteAclRule(ctx context.Context, siteId string, aclRuleId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/%s", siteId, aclRuleId)), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteAclRule: %w", err)
	}
	return nil
}

// DeleteDnsPolicy maps to DELETE /v1/sites/%s/dns/policies/%s on the Official API.
func (c *apiClient) DeleteDnsPolicy(ctx context.Context, siteId string, dnsPolicyId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies/%s", siteId, dnsPolicyId)), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteDnsPolicy: %w", err)
	}
	return nil
}

// DeleteFirewallPolicy maps to DELETE /v1/sites/%s/firewall/policies/%s on the Official API.
func (c *apiClient) DeleteFirewallPolicy(ctx context.Context, siteId string, firewallPolicyId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", siteId, firewallPolicyId)), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteFirewallPolicy: %w", err)
	}
	return nil
}

// DeleteFirewallZone maps to DELETE /v1/sites/%s/firewall/zones/%s on the Official API.
func (c *apiClient) DeleteFirewallZone(ctx context.Context, siteId string, firewallZoneId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones/%s", siteId, firewallZoneId)), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteFirewallZone: %w", err)
	}
	return nil
}

// DeleteNetwork maps to DELETE /v1/sites/%s/networks/%s on the Official API.
func (c *apiClient) DeleteNetwork(ctx context.Context, siteId string, networkId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s", siteId, networkId)), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteNetwork: %w", err)
	}
	return nil
}

// DeleteTrafficMatchingList maps to DELETE /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c *apiClient) DeleteTrafficMatchingList(ctx context.Context, siteId string, trafficMatchingListId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", siteId, trafficMatchingListId)), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteTrafficMatchingList: %w", err)
	}
	return nil
}

// DeleteVoucher maps to DELETE /v1/sites/%s/hotspot/vouchers/%s on the Official API.
func (c *apiClient) DeleteVoucher(ctx context.Context, siteId string, voucherId string) (*VoucherDeletionResults, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out VoucherDeletionResults
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/hotspot/vouchers/%s", siteId, voucherId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed DeleteVoucher: %w", err)
	}
	return &out, nil
}

// DeleteVouchers maps to DELETE /v1/sites/%s/hotspot/vouchers on the Official API.
func (c *apiClient) DeleteVouchers(ctx context.Context, siteId string, filter string) (*VoucherDeletionResults, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	if filter == "" {
		return nil, errors.New("filter must not be empty")
	}
	var out VoucherDeletionResults
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/hotspot/vouchers?filter=%s", siteId, url.QueryEscape(filter))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed DeleteVouchers: %w", err)
	}
	return &out, nil
}

// DeleteWifiBroadcast maps to DELETE /v1/sites/%s/wifi/broadcasts/%s on the Official API.
func (c *apiClient) DeleteWifiBroadcast(ctx context.Context, siteId string, wifiBroadcastId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/wifi/broadcasts/%s", siteId, wifiBroadcastId)), nil, nil); err != nil {
		return fmt.Errorf("failed DeleteWifiBroadcast: %w", err)
	}
	return nil
}

// ExecuteAdoptedDeviceAction maps to POST /v1/sites/%s/devices/%s/actions on the Official API.
func (c *apiClient) ExecuteAdoptedDeviceAction(ctx context.Context, siteId string, deviceId string, body DeviceActionRequest) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/actions", siteId, deviceId)), body, nil); err != nil {
		return fmt.Errorf("failed ExecuteAdoptedDeviceAction: %w", err)
	}
	return nil
}

// ExecuteConnectedClientAction maps to POST /v1/sites/%s/clients/%s/actions on the Official API.
func (c *apiClient) ExecuteConnectedClientAction(ctx context.Context, siteId string, clientId string, body ClientActionRequest) (*ClientActionResponse, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ClientActionResponse
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/clients/%s/actions", siteId, clientId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed ExecuteConnectedClientAction: %w", err)
	}
	return &out, nil
}

// ExecutePortAction maps to POST /v1/sites/%s/devices/%s/interfaces/ports/%s/actions on the Official API.
func (c *apiClient) ExecutePortAction(ctx context.Context, siteId string, deviceId string, portIdx string, body PortActionRequest) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Post(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/interfaces/ports/%s/actions", siteId, deviceId, portIdx)), body, nil); err != nil {
		return fmt.Errorf("failed ExecutePortAction: %w", err)
	}
	return nil
}

// GetAclRule maps to GET /v1/sites/%s/acl-rules/%s on the Official API.
func (c *apiClient) GetAclRule(ctx context.Context, siteId string, aclRuleId string) (*ACLRule, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRule
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/%s", siteId, aclRuleId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetAclRule: %w", err)
	}
	return &out, nil
}

// GetAclRuleOrdering maps to GET /v1/sites/%s/acl-rules/ordering on the Official API.
func (c *apiClient) GetAclRuleOrdering(ctx context.Context, siteId string) (*ACLRuleOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRuleOrdering
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/ordering", siteId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetAclRuleOrdering: %w", err)
	}
	return &out, nil
}

// GetAclRulePage maps to GET /v1/sites/%s/acl-rules on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetAclRulePage(ctx context.Context, siteId string) ([]ACLRuleObject, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []ACLRuleObject
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/acl-rules", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetAclRulePage: %w", err)
	}
	return out, nil
}

// GetAdoptedDeviceDetails maps to GET /v1/sites/%s/devices/%s on the Official API.
func (c *apiClient) GetAdoptedDeviceDetails(ctx context.Context, siteId string, deviceId string) (*AdoptedDeviceDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out AdoptedDeviceDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s", siteId, deviceId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetAdoptedDeviceDetails: %w", err)
	}
	return &out, nil
}

// GetAdoptedDeviceLatestStatistics maps to GET /v1/sites/%s/devices/%s/statistics/latest on the Official API.
func (c *apiClient) GetAdoptedDeviceLatestStatistics(ctx context.Context, siteId string, deviceId string) (*LatestStatisticsForADevice, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out LatestStatisticsForADevice
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s/statistics/latest", siteId, deviceId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetAdoptedDeviceLatestStatistics: %w", err)
	}
	return &out, nil
}

// GetAdoptedDeviceOverviewPage maps to GET /v1/sites/%s/devices on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetAdoptedDeviceOverviewPage(ctx context.Context, siteId string) ([]AdoptedDeviceOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []AdoptedDeviceOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/devices", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetAdoptedDeviceOverviewPage: %w", err)
	}
	return out, nil
}

// GetConnectedClientDetails maps to GET /v1/sites/%s/clients/%s on the Official API.
func (c *apiClient) GetConnectedClientDetails(ctx context.Context, siteId string, clientId string) (*ClientDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ClientDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/clients/%s", siteId, clientId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetConnectedClientDetails: %w", err)
	}
	return &out, nil
}

// GetConnectedClientOverviewPage maps to GET /v1/sites/%s/clients on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetConnectedClientOverviewPage(ctx context.Context, siteId string) ([]ClientOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []ClientOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/clients", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetConnectedClientOverviewPage: %w", err)
	}
	return out, nil
}

// GetCountries maps to GET /v1/countries on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetCountries(ctx context.Context) ([]CountryDefinition, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []CountryDefinition
	if err := listAll(ctx, c.doer, c.path("/countries"), &out); err != nil {
		return nil, fmt.Errorf("failed GetCountries: %w", err)
	}
	return out, nil
}

// GetDeviceTagPage maps to GET /v1/sites/%s/device-tags on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetDeviceTagPage(ctx context.Context, siteId string) ([]DeviceTag, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []DeviceTag
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/device-tags", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetDeviceTagPage: %w", err)
	}
	return out, nil
}

// GetDnsPolicy maps to GET /v1/sites/%s/dns/policies/%s on the Official API.
func (c *apiClient) GetDnsPolicy(ctx context.Context, siteId string, dnsPolicyId string) (*DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out DNSPolicy
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies/%s", siteId, dnsPolicyId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetDnsPolicy: %w", err)
	}
	return &out, nil
}

// GetDnsPolicyPage maps to GET /v1/sites/%s/dns/policies on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetDnsPolicyPage(ctx context.Context, siteId string) ([]DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []DNSPolicy
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/dns/policies", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetDnsPolicyPage: %w", err)
	}
	return out, nil
}

// GetDpiApplicationCategories maps to GET /v1/dpi/categories on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetDpiApplicationCategories(ctx context.Context) ([]DPICategory, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []DPICategory
	if err := listAll(ctx, c.doer, c.path("/dpi/categories"), &out); err != nil {
		return nil, fmt.Errorf("failed GetDpiApplicationCategories: %w", err)
	}
	return out, nil
}

// GetDpiApplications maps to GET /v1/dpi/applications on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetDpiApplications(ctx context.Context) ([]DPIApplication, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []DPIApplication
	if err := listAll(ctx, c.doer, c.path("/dpi/applications"), &out); err != nil {
		return nil, fmt.Errorf("failed GetDpiApplications: %w", err)
	}
	return out, nil
}

// GetFirewallPolicies maps to GET /v1/sites/%s/firewall/policies on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetFirewallPolicies(ctx context.Context, siteId string) ([]FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []FirewallPolicy
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/firewall/policies", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetFirewallPolicies: %w", err)
	}
	return out, nil
}

// GetFirewallPolicy maps to GET /v1/sites/%s/firewall/policies/%s on the Official API.
func (c *apiClient) GetFirewallPolicy(ctx context.Context, siteId string, firewallPolicyId string) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", siteId, firewallPolicyId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetFirewallPolicy: %w", err)
	}
	return &out, nil
}

// GetFirewallPolicyOrdering maps to GET /v1/sites/%s/firewall/policies/ordering on the Official API.
func (c *apiClient) GetFirewallPolicyOrdering(ctx context.Context, siteId string, sourceFirewallZoneId string, destinationFirewallZoneId string) (*FirewallPolicyOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicyOrdering
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/ordering?sourceFirewallZoneId=%s&destinationFirewallZoneId=%s", siteId, url.QueryEscape(sourceFirewallZoneId), url.QueryEscape(destinationFirewallZoneId))), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetFirewallPolicyOrdering: %w", err)
	}
	return &out, nil
}

// GetFirewallZone maps to GET /v1/sites/%s/firewall/zones/%s on the Official API.
func (c *apiClient) GetFirewallZone(ctx context.Context, siteId string, firewallZoneId string) (*FirewallZone, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallZone
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones/%s", siteId, firewallZoneId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetFirewallZone: %w", err)
	}
	return &out, nil
}

// GetFirewallZones maps to GET /v1/sites/%s/firewall/zones on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetFirewallZones(ctx context.Context, siteId string) ([]FirewallZone, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []FirewallZone
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/firewall/zones", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetFirewallZones: %w", err)
	}
	return out, nil
}

// GetNetworkDetails maps to GET /v1/sites/%s/networks/%s on the Official API.
func (c *apiClient) GetNetworkDetails(ctx context.Context, siteId string, networkId string) (*NetworkDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s", siteId, networkId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetNetworkDetails: %w", err)
	}
	return &out, nil
}

// GetNetworkReferences maps to GET /v1/sites/%s/networks/%s/references on the Official API.
func (c *apiClient) GetNetworkReferences(ctx context.Context, siteId string, networkId string) (*NetworkReferences, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkReferences
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s/references", siteId, networkId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetNetworkReferences: %w", err)
	}
	return &out, nil
}

// GetNetworksOverviewPage maps to GET /v1/sites/%s/networks on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetNetworksOverviewPage(ctx context.Context, siteId string) ([]NetworkOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []NetworkOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/networks", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetNetworksOverviewPage: %w", err)
	}
	return out, nil
}

// GetPendingDevicePage maps to GET /v1/pending-devices on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetPendingDevicePage(ctx context.Context) ([]DevicePendingAdoption, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []DevicePendingAdoption
	if err := listAll(ctx, c.doer, c.path("/pending-devices"), &out); err != nil {
		return nil, fmt.Errorf("failed GetPendingDevicePage: %w", err)
	}
	return out, nil
}

// GetRadiusProfileOverviewPage maps to GET /v1/sites/%s/radius/profiles on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetRadiusProfileOverviewPage(ctx context.Context, siteId string) ([]RadiusProfileOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []RadiusProfileOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/radius/profiles", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetRadiusProfileOverviewPage: %w", err)
	}
	return out, nil
}

// GetSiteToSiteVpnTunnelPage maps to GET /v1/sites/%s/vpn/site-to-site-tunnels on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetSiteToSiteVpnTunnelPage(ctx context.Context, siteId string) ([]SiteToSiteVPNTunnelOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []SiteToSiteVPNTunnelOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/vpn/site-to-site-tunnels", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetSiteToSiteVpnTunnelPage: %w", err)
	}
	return out, nil
}

// GetTrafficMatchingList maps to GET /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c *apiClient) GetTrafficMatchingList(ctx context.Context, siteId string, trafficMatchingListId string) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", siteId, trafficMatchingListId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetTrafficMatchingList: %w", err)
	}
	return &out, nil
}

// GetTrafficMatchingLists maps to GET /v1/sites/%s/traffic-matching-lists on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetTrafficMatchingLists(ctx context.Context, siteId string) ([]TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []TrafficMatchingList
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetTrafficMatchingLists: %w", err)
	}
	return out, nil
}

// GetVoucher maps to GET /v1/sites/%s/hotspot/vouchers/%s on the Official API.
func (c *apiClient) GetVoucher(ctx context.Context, siteId string, voucherId string) (*HotspotVoucherDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out HotspotVoucherDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/hotspot/vouchers/%s", siteId, voucherId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetVoucher: %w", err)
	}
	return &out, nil
}

// GetVouchers maps to GET /v1/sites/%s/hotspot/vouchers on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetVouchers(ctx context.Context, siteId string) ([]HotspotVoucherDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []HotspotVoucherDetails
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/hotspot/vouchers", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetVouchers: %w", err)
	}
	return out, nil
}

// GetVpnServerPage maps to GET /v1/sites/%s/vpn/servers on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetVpnServerPage(ctx context.Context, siteId string) ([]VPNServerOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []VPNServerOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/vpn/servers", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetVpnServerPage: %w", err)
	}
	return out, nil
}

// GetWansOverviewPage maps to GET /v1/sites/%s/wans on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetWansOverviewPage(ctx context.Context, siteId string) ([]WANOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []WANOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/wans", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetWansOverviewPage: %w", err)
	}
	return out, nil
}

// GetWifiBroadcastDetails maps to GET /v1/sites/%s/wifi/broadcasts/%s on the Official API.
func (c *apiClient) GetWifiBroadcastDetails(ctx context.Context, siteId string, wifiBroadcastId string) (*WifiBroadcastDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out WifiBroadcastDetails
	if err := c.doer.Get(ctx, c.path(fmt.Sprintf("/sites/%s/wifi/broadcasts/%s", siteId, wifiBroadcastId)), nil, &out); err != nil {
		return nil, fmt.Errorf("failed GetWifiBroadcastDetails: %w", err)
	}
	return &out, nil
}

// GetWifiBroadcastPage maps to GET /v1/sites/%s/wifi/broadcasts on the Official API. Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items.
func (c *apiClient) GetWifiBroadcastPage(ctx context.Context, siteId string) ([]WifiBroadcastOverview, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out []WifiBroadcastOverview
	if err := listAll(ctx, c.doer, c.path(fmt.Sprintf("/sites/%s/wifi/broadcasts", siteId)), &out); err != nil {
		return nil, fmt.Errorf("failed GetWifiBroadcastPage: %w", err)
	}
	return out, nil
}

// PatchFirewallPolicy maps to PATCH /v1/sites/%s/firewall/policies/%s on the Official API.
func (c *apiClient) PatchFirewallPolicy(ctx context.Context, siteId string, firewallPolicyId string, body PatchFirewallPolicy) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Patch(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", siteId, firewallPolicyId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed PatchFirewallPolicy: %w", err)
	}
	return &out, nil
}

// RemoveDevice maps to DELETE /v1/sites/%s/devices/%s on the Official API.
func (c *apiClient) RemoveDevice(ctx context.Context, siteId string, deviceId string) error {
	if err := c.check(ctx); err != nil {
		return err
	}
	if err := c.doer.Delete(ctx, c.path(fmt.Sprintf("/sites/%s/devices/%s", siteId, deviceId)), nil, nil); err != nil {
		return fmt.Errorf("failed RemoveDevice: %w", err)
	}
	return nil
}

// UpdateAclRule maps to PUT /v1/sites/%s/acl-rules/%s on the Official API.
func (c *apiClient) UpdateAclRule(ctx context.Context, siteId string, aclRuleId string, body ACLRuleUpdate) (*ACLRule, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRule
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/%s", siteId, aclRuleId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateAclRule: %w", err)
	}
	return &out, nil
}

// UpdateAclRuleOrdering maps to PUT /v1/sites/%s/acl-rules/ordering on the Official API.
func (c *apiClient) UpdateAclRuleOrdering(ctx context.Context, siteId string, body ACLRuleOrdering) (*ACLRuleOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out ACLRuleOrdering
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/acl-rules/ordering", siteId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateAclRuleOrdering: %w", err)
	}
	return &out, nil
}

// UpdateDnsPolicy maps to PUT /v1/sites/%s/dns/policies/%s on the Official API.
func (c *apiClient) UpdateDnsPolicy(ctx context.Context, siteId string, dnsPolicyId string, body DNSPolicyCreateOrUpdate) (*DNSPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out DNSPolicy
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/dns/policies/%s", siteId, dnsPolicyId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateDnsPolicy: %w", err)
	}
	return &out, nil
}

// UpdateFirewallPolicy maps to PUT /v1/sites/%s/firewall/policies/%s on the Official API.
func (c *apiClient) UpdateFirewallPolicy(ctx context.Context, siteId string, firewallPolicyId string, body FirewallPolicyCreateOrUpdate) (*FirewallPolicy, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicy
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/%s", siteId, firewallPolicyId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateFirewallPolicy: %w", err)
	}
	return &out, nil
}

// UpdateFirewallPolicyOrdering maps to PUT /v1/sites/%s/firewall/policies/ordering on the Official API.
func (c *apiClient) UpdateFirewallPolicyOrdering(ctx context.Context, siteId string, sourceFirewallZoneId string, destinationFirewallZoneId string, body FirewallPolicyOrdering) (*FirewallPolicyOrdering, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallPolicyOrdering
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/policies/ordering?sourceFirewallZoneId=%s&destinationFirewallZoneId=%s", siteId, url.QueryEscape(sourceFirewallZoneId), url.QueryEscape(destinationFirewallZoneId))), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateFirewallPolicyOrdering: %w", err)
	}
	return &out, nil
}

// UpdateFirewallZone maps to PUT /v1/sites/%s/firewall/zones/%s on the Official API.
func (c *apiClient) UpdateFirewallZone(ctx context.Context, siteId string, firewallZoneId string, body FirewallZoneCreateOrUpdate) (*FirewallZone, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out FirewallZone
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/firewall/zones/%s", siteId, firewallZoneId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateFirewallZone: %w", err)
	}
	return &out, nil
}

// UpdateNetwork maps to PUT /v1/sites/%s/networks/%s on the Official API.
func (c *apiClient) UpdateNetwork(ctx context.Context, siteId string, networkId string, body NetworkCreateOrUpdate) (*NetworkDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out NetworkDetails
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/networks/%s", siteId, networkId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateNetwork: %w", err)
	}
	return &out, nil
}

// UpdateTrafficMatchingList maps to PUT /v1/sites/%s/traffic-matching-lists/%s on the Official API.
func (c *apiClient) UpdateTrafficMatchingList(ctx context.Context, siteId string, trafficMatchingListId string, body TrafficMatchingListCreateOrUpdate) (*TrafficMatchingList, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out TrafficMatchingList
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/traffic-matching-lists/%s", siteId, trafficMatchingListId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateTrafficMatchingList: %w", err)
	}
	return &out, nil
}

// UpdateWifiBroadcast maps to PUT /v1/sites/%s/wifi/broadcasts/%s on the Official API.
func (c *apiClient) UpdateWifiBroadcast(ctx context.Context, siteId string, wifiBroadcastId string, body WifiBroadcastCreateOrUpdate) (*WifiBroadcastDetails, error) {
	if err := c.check(ctx); err != nil {
		return nil, err
	}
	var out WifiBroadcastDetails
	if err := c.doer.Put(ctx, c.path(fmt.Sprintf("/sites/%s/wifi/broadcasts/%s", siteId, wifiBroadcastId)), body, &out); err != nil {
		return nil, fmt.Errorf("failed UpdateWifiBroadcast: %w", err)
	}
	return &out, nil
}
