package main

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// modulePath is the generator's import path, used in the DO-NOT-EDIT banner so
// the official surface files match the models file's header form.
const modulePath = "github.com/filipowm/go-unifi/codegen/official"

// doerMethods maps an HTTP verb to the official.Doer method that performs it.
var doerMethods = map[string]string{
	"GET": "Get", "POST": "Post", "PUT": "Put", "DELETE": "Delete", "PATCH": "Patch",
}

// handWrittenMethods are the surface methods implemented by hand (info.go,
// sites.go). They carry no generated wrapper body but MUST appear in the Client
// interface and its mock, so the generated surface is the single source of truth.
var handWrittenMethods = []method{
	{Name: "GetInfo", Doc: "returns the controller application info (GET /v1/info).", Params: []arg{ctxArg}, Returns: []string{"*Info", "error"}},
	{Name: "ListSites", Doc: "returns all local sites, auto-paginating the list envelope.", Params: []arg{ctxArg}, Returns: []string{"[]SiteOverview", "error"}},
	{Name: "ResolveSiteID", Doc: "maps a legacy site name to its Official-API site UUID, caching the lookup.", Params: []arg{ctxArg, {Name: "name", Type: "string"}}, Returns: []string{"string", "error"}},
}

// ctxArg is the leading context argument shared by every surface method.
var ctxArg = arg{Name: "ctx", Type: "context.Context"}

// arg is a single method parameter.
type arg struct{ Name, Type string }

// method is the unified view a generated wrapper, an interface entry, and a mock
// entry are all rendered from, so the three stay in lockstep.
type method struct {
	Name    string
	Doc     string // godoc body; the rendered comment is "// <Name> <Doc>"
	Params  []arg
	Returns []string   // Go return types, terminal element is always "error"
	op      *operation // nil for hand-written methods (interface/mock only)
}

// methods returns the full surface — generated operations plus the hand-written
// methods — sorted by name for deterministic output.
func methods(ops []operation) []method {
	all := make([]method, 0, len(ops)+len(handWrittenMethods))
	all = append(all, handWrittenMethods...)
	for i := range ops {
		all = append(all, methodFor(ops[i]))
	}
	sort.Slice(all, func(i, j int) bool { return all[i].Name < all[j].Name })
	return all
}

// methodFor lifts an operation into the unified method view.
func methodFor(op operation) method {
	o := op
	m := method{Name: op.Name, Doc: docFor(op), op: &o}
	m.Params = append(m.Params, ctxArg)
	for _, p := range op.PathArgs {
		m.Params = append(m.Params, arg{Name: p.Name, Type: "string"})
	}
	for _, q := range op.QueryArgs {
		m.Params = append(m.Params, arg{Name: q.Name, Type: "string"})
	}
	if op.BodyType != "" {
		m.Params = append(m.Params, arg{Name: "body", Type: op.BodyType})
	}
	switch {
	case op.IsList():
		m.Returns = []string{"[]" + op.ItemType, "error"}
	case op.ReturnType != "":
		m.Returns = []string{"*" + op.ReturnType, "error"}
	default:
		m.Returns = []string{"error"}
	}
	return m
}

// docFor builds the godoc body for an operation method.
// List shapes append an auto-pagination notice so callers see the cost at the call site.
func docFor(op operation) string {
	base := fmt.Sprintf("maps to %s /v1%s on the Official API.", op.HTTPMethod, op.SubPath)
	if op.IsList() {
		return base + " Auto-paginates the offset/limit envelope (up to maxPageLimit per request), returning all items."
	}
	return base
}

// valueReturn reports whether the method returns a value alongside its error
// (so failure paths must return a leading zero value).
func (m method) valueReturn() bool { return len(m.Returns) > 1 }

// zeroPrefix is the leading return operand(s) on an error path: "nil, " for a
// value-returning method, empty for an error-only one.
func (m method) zeroPrefix() string {
	if m.valueReturn() {
		return "nil, "
	}
	return ""
}

// signature renders the interface/wrapper signature, e.g.
// "GetNetworkDetails(ctx context.Context, siteId string) (*NetworkDetails, error)".
func (m method) signature() string {
	parts := make([]string, len(m.Params))
	for i, p := range m.Params {
		parts[i] = p.Name + " " + p.Type
	}
	ret := m.Returns[0]
	if len(m.Returns) > 1 {
		ret = "(" + strings.Join(m.Returns, ", ") + ")"
	}
	return fmt.Sprintf("%s(%s) %s", m.Name, strings.Join(parts, ", "), ret)
}

// banner is the shared DO-NOT-EDIT header for every generated surface file.
func banner() string {
	return fmt.Sprintf("// Code generated by %s version %s DO NOT EDIT.", modulePath, generatorVersion)
}

// generateWrappers renders the tri-shape wrapper methods on *apiClient.
func generateWrappers(ops []operation, pkg string) (string, error) {
	usesURL, usesErrors := false, false
	for i := range ops {
		// Both path and query args are URL-escaped, so either pulls in net/url.
		if len(ops[i].QueryArgs) > 0 || len(ops[i].PathArgs) > 0 {
			usesURL = true
		}
		if ops[i].RequiredFilter() != "" {
			usesErrors = true
		}
	}
	var b strings.Builder
	b.WriteString(banner())
	b.WriteString("\n\npackage " + pkg + "\n\nimport (\n\t\"context\"\n")
	if usesErrors {
		b.WriteString("\t\"errors\"\n")
	}
	b.WriteString("\t\"fmt\"\n")
	if usesURL {
		b.WriteString("\t\"net/url\"\n")
	}
	b.WriteString(")\n")

	sorted := append([]operation(nil), ops...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	for i := range sorted {
		b.WriteString("\n")
		b.WriteString(wrapperBody(methodFor(sorted[i])))
	}
	return formatGo(b.String())
}

// wrapperBody renders one wrapper method, dispatching on its shape.
func wrapperBody(m method) string {
	op := m.op
	zero := m.zeroPrefix()
	var b strings.Builder
	fmt.Fprintf(&b, "// %s %s\n", m.Name, m.Doc)
	fmt.Fprintf(&b, "func (c *apiClient) %s {\n", m.signature())
	fmt.Fprintf(&b, "\tif err := c.check(ctx); err != nil {\n\t\treturn %serr\n\t}\n", zero)
	if f := op.RequiredFilter(); f != "" {
		fmt.Fprintf(&b, "\tif %s == \"\" {\n\t\treturn %serrors.New(%q)\n\t}\n", f, zero, f+" must not be empty")
	}
	path := pathExpr(*op)
	switch {
	case op.IsList():
		fmt.Fprintf(&b, "\tvar out []%s\n", op.ItemType)
		fmt.Fprintf(&b, "\tif err := listAll(ctx, c.doer, c.path(%s), &out); err != nil {\n", path)
		fmt.Fprintf(&b, "\t\treturn nil, fmt.Errorf(%q, err)\n\t}\n", "failed "+m.Name+": %w")
		b.WriteString("\treturn out, nil\n")
	case op.ReturnType != "":
		fmt.Fprintf(&b, "\tvar out %s\n", op.ReturnType)
		fmt.Fprintf(&b, "\tif err := c.doer.%s(ctx, c.path(%s), %s, &out); err != nil {\n", doerMethods[op.HTTPMethod], path, reqArg(*op))
		fmt.Fprintf(&b, "\t\treturn nil, fmt.Errorf(%q, err)\n\t}\n", "failed "+m.Name+": %w")
		b.WriteString("\treturn &out, nil\n")
	default:
		fmt.Fprintf(&b, "\tif err := c.doer.%s(ctx, c.path(%s), %s, nil); err != nil {\n", doerMethods[op.HTTPMethod], path, reqArg(*op))
		fmt.Fprintf(&b, "\t\treturn fmt.Errorf(%q, err)\n\t}\n", "failed "+m.Name+": %w")
		b.WriteString("\treturn nil\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// reqArg is the request-body operand passed to the Doer call.
func reqArg(op operation) string {
	if op.BodyType != "" {
		return "body"
	}
	return "nil"
}

// pathExpr renders the Go expression for the request sub-path: a string literal
// when fully static, else an fmt.Sprintf over the path and required-query args.
func pathExpr(op operation) string {
	if len(op.PathArgs) == 0 && len(op.QueryArgs) == 0 {
		return fmt.Sprintf("%q", op.SubPath)
	}
	var format strings.Builder
	format.WriteString(op.SubPath)
	args := make([]string, 0, len(op.PathArgs)+len(op.QueryArgs))
	// Escape path segments: an ID containing '/', '?' or '#' must not alter the route.
	for _, p := range op.PathArgs {
		args = append(args, "url.PathEscape("+p.Name+")")
	}
	for i, q := range op.QueryArgs {
		sep := "&"
		if i == 0 {
			sep = "?"
		}
		fmt.Fprintf(&format, "%s%s=%%s", sep, q.Name)
		args = append(args, "url.QueryEscape("+q.Name+")")
	}
	return fmt.Sprintf("fmt.Sprintf(%q, %s)", format.String(), strings.Join(args, ", "))
}

// generateClient renders the Client interface over the full surface.
func generateClient(ops []operation, pkg string) (string, error) {
	var b strings.Builder
	b.WriteString(banner())
	b.WriteString("\n\npackage " + pkg + "\n\nimport \"context\"\n\n")
	b.WriteString("// Client is the Official UniFi OpenAPI (integration/v1) surface.\n")
	b.WriteString("type Client interface {\n")
	for _, m := range methods(ops) {
		fmt.Fprintf(&b, "\t// %s %s\n\t%s\n", m.Name, m.Doc, m.signature())
	}
	b.WriteString("}\n")
	return formatGo(b.String())
}

// generateMock renders a hand-rolled func-field mock of Client. A bare double
// (no moq dependency) keeps the isolated module's dep graph minimal.
func generateMock(ops []operation, pkg string) (string, error) {
	all := methods(ops)
	var b strings.Builder
	b.WriteString(banner())
	b.WriteString("\n\npackage " + pkg + "\n\nimport \"context\"\n\n")
	b.WriteString("// ClientMock is a func-field test double implementing Client. A nil field\n")
	b.WriteString("// panics on call, surfacing an un-stubbed method in tests.\n")
	b.WriteString("type ClientMock struct {\n")
	for _, m := range all {
		fmt.Fprintf(&b, "\t%sFunc func(%s) %s\n", m.Name, mockParams(m), mockReturns(m))
	}
	b.WriteString("}\n\n")
	b.WriteString("var _ Client = (*ClientMock)(nil)\n")
	for _, m := range all {
		fmt.Fprintf(&b, "\nfunc (m *ClientMock) %s {\n\treturn m.%sFunc(%s)\n}\n", m.signature(), m.Name, callArgs(m))
	}
	return formatGo(b.String())
}

// mockParams renders the func-field parameter types (no names).
func mockParams(m method) string {
	types := make([]string, len(m.Params))
	for i, p := range m.Params {
		types[i] = p.Type
	}
	return strings.Join(types, ", ")
}

// mockReturns renders the func-field return clause.
func mockReturns(m method) string {
	if len(m.Returns) > 1 {
		return "(" + strings.Join(m.Returns, ", ") + ")"
	}
	return m.Returns[0]
}

// callArgs renders the argument names forwarded to the stub func.
func callArgs(m method) string {
	names := make([]string, len(m.Params))
	for i, p := range m.Params {
		names[i] = p.Name
	}
	return strings.Join(names, ", ")
}

// formatGo gofmt-formats generated source, surfacing a clear error on bad output.
func formatGo(src string) (string, error) {
	out, err := format.Source([]byte(src))
	if err != nil {
		return "", fmt.Errorf("formatting generated source: %w", err)
	}
	return string(out), nil
}
