---
name: "Conventional Release Labels"
on:
  pull_request_target:
    types:
      - "opened"
      - "edited"
jobs:
  label:
    permissions:
      pull-requests: "write"
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "bcoe/conventional-release-labels@v1"
